### ISSUE TITLE
Card #121

### ISSUE THREAD

**Issue by mplain** [Kamalisk/arkhamdb#10]
Figure out what to do with it. Maybe separating all double-sided cards into two separate cards isn't worth it.

**Comment by soulb1ight** [comment]
Clicking either "Predator or Prey?" or "The Masked Hunter" leads to a page that says 
"Your query didn't match any card."
http://arkhamdb.com/card/01121a - no card
http://arkhamdb.com/card/01121b - no card
http://arkhamdb.com/card/01121 - page doesn't exist
They also aren't searchable.

**Comment by jtesorie** [comment]
Card should have Doom 6, but it's listed as 8.

**Comment by mplain** [comment]
Thanks, i'll fix that.

**Comment by Kamalisk** [comment]
So, linked cards are now possible. I have updated the json and arkhamdb for some of them, I am unsure which cards are doubled sided (I am avoiding most spoilers until I play the new scenarios)

You should see how to link cards in the json. It has to link to a card that exists. 

The important thing is that the face of the card it the card to be linked to the back, and the back should be set to hidden. Search should search both the front and back for most fields, it shows both cards on the card page, and many cards can be linked to one card.
