### ISSUE TITLE
Lucky Dice reporting incorrect xp

### ISSUE THREAD

**Issue by howlingfang** [Kamalisk/arkhamdb#101]
I am using Jenny Barnes  - didn't test with other investigators.  Lucky dice shows to XP cost pips (correctly) in UI and on mouse over but when I add it to my deck it is registering as 4xp not 2xp.

![image](https://user-images.githubusercontent.com/4806109/27012796-f9f025d8-4e94-11e7-9c8a-087d3fbf2acb.png)

**Comment by Kamalisk** [comment]
that is because it is Exceptional (costs double the printed xp value)

**Comment by howlingfang** [comment]
Oops.  Thanks.
