### ISSUE TITLE
Cannot search for decks which use only one core set

### ISSUE THREAD

**Issue by rcambrj** [Kamalisk/arkhamdb#104]
I want to find a deck to use which is compatible with my collection.

In my collection I've specified one core set and a bunch of expansions.

Sadly, when I search, for decks I mostly get decks which use two core sets, there is no way to filter by _one core set_.

**Comment by Kamalisk** [comment]
so much harder to fix than it should be

**Comment by rcambrj** [comment]
Yeah I saw. I'm a bit rusty with my Symfony (haven't touched PHP in a good few years) but I could establish that this is no trivial thing to fix.

**Comment by Kamalisk** [comment]
Should be able to search single cores now.
