### ISSUE TITLE
In iOS, 'Card Search' doesn't have a submit

### ISSUE THREAD

**Issue by andrewwburns** [Kamalisk/arkhamdb#112]
In iOS, if I use the burger menu and choose 'Card Search', I can enter a search, but the 'Go' button doesn't cause a submit, and there's no submit button:

![image](https://user-images.githubusercontent.com/13449428/28366901-85b37be2-6c86-11e7-87e0-02afbd15a74a.png)

I've scrolled around; there doesn't seem to be a way of actually initiating a search...

Note: This does work correctly in Chrome impersonating an iOS device.

**Comment by Kamalisk** [comment]
I have no way to test this. But it seems that it is probably the target=_blank which causes the problem and it just silently doesnt do anything on iOS. The search is meant to open in a new window to avoid  causing issues if you search while deck building.
