### ISSUE TITLE
Marie Lambeau - Spell Cards Level 5

### ISSUE THREAD

**Issue by DavFlamerock** [Kamalisk/arkhamdb#114]
Hello! Was just building an upgraded Marie Lambeau deck, and it looks like it's set to only allow Mystic Cards lvl 0-3, but not Spell Cards lvl 0-5. Shriveling Lvl 5 is a valid choice!

Thanks :)
~Dav

**Comment by Kamalisk** [comment]
fixed. might require a proper page reload.
