### ISSUE TITLE
Enemy (weakness) cards are missing from exported Text file decks

### ISSUE THREAD

**Issue by A1win** [Kamalisk/arkhamdb#116]
When using the Download button on a deck page to download that deck as a "Text file", all Enemy type cards included in the deck are missing from the exported file. For Octgn files this works as intended.

This can be reproduced with any or all of the three basic weakness enemy cards included in the deck: Mob Enforcer, Silver Twilight Acolyte, and Stubborn Detective.

![image](https://user-images.githubusercontent.com/30815389/29051367-d2e8b01c-7bea-11e7-9f09-225d21507e52.png)

![image](https://user-images.githubusercontent.com/30815389/29051428-52fe81be-7beb-11e7-973e-e2f312ff252c.png)

![image](https://user-images.githubusercontent.com/30815389/29051445-68c0e384-7beb-11e7-94a8-423c7ee8c4c3.png)

**Comment by Kamalisk** [comment]
should have been fixed.
