### ISSUE TITLE
Weaknesses

### ISSUE THREAD

**Issue by mplain** [Kamalisk/arkhamdb#13]
- Implement Search by subtype: Weakness (all) or Basic Weakness.

- suggestion: In the deckbuilder, have a general "Random Weakness" option available (would be cool if it added an actual random weakness every time you save the deck in OCTGN format)

- suggestion: Redistribute 'Special Weaknesses' between 'Signature' and 'Campaign'
i.e. 'Signature' will only have 1 signature card and 1 signature weakness specific to the chosen investigator (not class, like now!), and 'Campaign' will have acquired weaknesses and story assets both.

**Comment by mattsigal** [comment]
See 153ee0108447ee00966a14c3e8ff57400fe7f586

**Comment by Kamalisk** [comment]
Probably not going to let you search for both weaknesses and basic weaknesses at same time, and the other options are done mostly, the random basic weakness when ocgtn saved may or may not be a good idea, but will close this for now
