### ISSUE TITLE
Heroic Rescue doesn't seem to be available to Guardians

### ISSUE THREAD

**Issue by andrewwburns** [Kamalisk/arkhamdb#130]
Neither my Mark or Roland decks seem to be able to add it - but it does seem to be in the database...

**Comment by Kamalisk** [comment]
have you selected the pack in the deck builder (or in your collection?)

**Comment by andrewwburns** [comment]
Weird. I didn't change anything - but it's there now. I am using a different machine. Caching issue?

**Comment by Kamalisk** [comment]
it can be a caching issue.
