### ISSUE TITLE
Replacement cards

### ISSUE THREAD

**Issue by jmccluey** [Kamalisk/arkhamdb#132]
Newly released cards with the _Replacement_ keyword allow a player to replace or add signature cards for an investigator when deckbuilding.

The only currently released _Replacement_ cards (i.e., "Green Man Medallion" and "Sacrificial Beast" for Jenny Barnes) are not currently in the database.  They would either need a new collection section (perhaps "Arkham Horror Novellas") or could simply be added to "Promos".

The deckbuilder would need to handle "required" cards differently to account for the replacement or addition of signature cards.

**Comment by Kamalisk** [comment]
can manually change to replacement cards (or add them in addition)
