### ISSUE TITLE
Show Progress/Changes in Chrome

### ISSUE THREAD

**Issue by jacobbs** [Kamalisk/arkhamdb#133]
When I'm looking at one of my upgraded decks on my mobile device or in IE or Firefox, it has a very handy Progress and Changes section at the bottom so you can see what you had changed between versions. But when viewing it in Chrome, those sections aren't present.  Is that something that can be fixed/changed?  Is there some configuration that needs to be changed for Chrome?

Thanks!

**Comment by Kamalisk** [comment]
Are they not present in the tabs in chrome? I dont know why it would not show up in chrome specifically.

**Comment by jacobbs** [comment]
It is the strangest thing.  Here's the view from IE (11.0.9600.18837)

![image](https://user-images.githubusercontent.com/19996436/33435210-988b5f68-d5af-11e7-9417-4307446abdc9.png)

And here is the same deck from Chrome (62.0.3202.94)

![image](https://user-images.githubusercontent.com/19996436/33435339-f4b2b110-d5af-11e7-882c-b1e72a7382db.png)

Notice that the Progress and Change sections are just not there.  In fact the whole view is quite different (and nicer) in IE.

**Comment by Kamalisk** [comment]
You have set the sort order to be different in chrome. (only the sort by type view shows the changes). Looks like you are sorting by cost.
