### ISSUE TITLE
Should permanents be included in charts for draw deck?

### ISSUE THREAD

**Issue by kelsin** [Kamalisk/arkhamdb#134]
On my current Lola deck it's saying I have 9 Guardian cards from my draw deck when one of them is a permanent. Is this intended? https://arkhamdb.com/deck/view/91006

If permanents are meant to be considered draw deck then no bug here and we can close this.

It seems weird that permanents are listed with the forced cards for the investigator, but also included in draw stats.

Thanks for the amazing site btw, love it 👍

**Comment by Kamalisk** [comment]
should not be included in the stats now
