### ISSUE TITLE
Cannot publish deck

### ISSUE THREAD

**Issue by Chilavert82IT** [Kamalisk/arkhamdb#137]
When I try to post a new deck, this error message appears:

"You cannot publish this deck yet, because it has unreleased cards."

What's the reason? Maybe it's because there are some cards of the last chapter? But right now it's legal. This is a cooperative game, this kind of restriction is pretty useless.

**Comment by Kamalisk** [comment]
the cards are flagged as unreleased until they have been verified. Publishing a deck is for sharing with the community and asking for feedback. If you want to share a deck with friends you can do so by enabling sharing in the options, or wait until they are flagged for release.
I dont want to allow future spoilers to be posted in decks until they are released so the system will remain as is.
