### ISSUE TITLE
Card reference doesn't work - can't edit a submitted comment

### ISSUE THREAD

**Issue by DevGizmo86** [Kamalisk/arkhamdb#140]
It would be nice to edit a submitted comment... I recently submit a comment, but the references to the cards that I have inserted with the # don't work, and I would like to fix my comment!

https://arkhamdb.com/decklist/view/4147/vive-la-branche-1.0
Here you can view my comment with the element list (I've used `<ul><li>` standard html to make the list), where I can't see the card link...

**Comment by Kamalisk** [comment]
If you use html, the simple card links stop working.

**Comment by DevGizmo86** [comment]
Ok! Can I edit my comment to fix it?
