### ISSUE TITLE
Deck cannot be published due to unreleased cards

### ISSUE THREAD

**Issue by egoitzu** [Kamalisk/arkhamdb#142]
Hi Team,

There are decks with cards from the latest Black Star Rises mythos pack that throw this error when trying to publish:
"You cannot publish this deck yet, because it has unreleased cards."

Example:
https://arkhamdb.com/deck/view/120016

Is this a bug or is it due to the pack not being updated on the site?

Many Thanks!
Eggy

**Comment by Kamalisk** [comment]
the pack gets updated to released once all cards have been checked over. This means it is not always going to be as soon as the pack is actually released. They get flagged as released eventually.
