### ISSUE TITLE
Thumbnails missing in 2/3 column view

### ISSUE THREAD

**Issue by chrisheart86** [Kamalisk/arkhamdb#144]
Hi,

when I'm at the deck editor section and display the cards on 2 or 3 columns there are a lot of card thumbnails broken/not loading (both in Chrome and Firefox).

![kepernyofoto 2018-03-12 - 13 03 26](https://user-images.githubusercontent.com/8209919/37282775-f42c7f50-25f5-11e8-83a7-8814f9d83240.jpg)

**Comment by Kamalisk** [comment]
some of the images are png and some are jpg. Fixed it so it falls back to the other if it cant find it.
