### ISSUE TITLE
First Aid issue

### ISSUE THREAD

**Issue by Amilianna** [Kamalisk/arkhamdb#146]
When trying to build my deck for Roland Banks, I am only able to add one copy of the zero level blue card First Aid. I do not get an option to add a second copy. It is the first card I am adding. I can add 2 of the level 3 version of the same card.

**Comment by PlaidOsyluth** [comment]
When you were adding cards, did you check that your pack filter had the second core set checked? Each core set only has one copy of level 0 First Aid. I suspect that's what is going on.

**Comment by Kamalisk** [comment]
I assume this is because of the core set thing. If selecting a second core set doesnt solve the issue, open it again.
