### ISSUE TITLE
Carnevale of horrors

### ISSUE THREAD

**Issue by clippermonkey** [Kamalisk/arkhamdb#149]
According to the setup instruction for this scenario. The encounters set is called 'carnevale of horrors' not Venice as listed on the arkhamdb.
A small mistake, but has proven problematic having the wrong name listed on arkhamdb, when referencing deckbuilding and questions on other sites.
Can this error be changed to use the encounter set's actual name?

**Comment by Kamalisk** [comment]
should be fixed
