### ISSUE TITLE
Sort Cards in Decklist View

### ISSUE THREAD

**Issue by mattsigal** [Kamalisk/arkhamdb#15]
When browsing a decklist or creating one, right now ArkhamDB only sorts cards by Type (Asset/Event/Skill), and I'm not actually even sure what the secondary sort is by, to be honest.

It would be great if this could be modified to act similar to netrunnerdb: where we could sort the decklist by things like: card number, faction, et cetera. Similar to: 
![screen shot 2016-11-11 at 20 55 54](https://cloud.githubusercontent.com/assets/1421758/20234866/4908d39e-a851-11e6-9255-540b209e819c.png)

I know that I have my cards sorted by faction then card number, so that particular combination would be very useful for me!

**Comment by jayelbird** [comment]
Sort by exp cost?

**Comment by mattsigal** [comment]
Yeah, off the top of my head, I think we should have the option to sort by:

-Card Type, then Alphabetical -- as the default, which is similar to what we have now but with the additional alphabetical stipulation
-Faction, then Alphabetical
-Faction, then by Card Number -- this is actually the method I think would be most popular, as I think many players will store their player cards in this manner.
-By Card Number (this and the previous method will differentiate themselves once expansions are in the mix) 
-By XP cost
-By Play cost
-By Name (pure alphabetical sorting)

I would hope this would be available both when viewing private decks, when editing private decks, and while viewing published decks.

**Comment by Kamalisk** [comment]
Sort is added on decklists and viewing your own decks. Not on editing a deck yet.

**Comment by Kamalisk** [comment]
added sort to deck edit page. 
added lots of sort options.
