### ISSUE TITLE
Calvin Wright Deck Restrictions are not Permitting Decks to be Published

### ISSUE THREAD

**Issue by Soakman** [Kamalisk/arkhamdb#152]
Hello!

Not sure, but it seems like Calvin Wright decks are unable to be published at this time. I don't see any saved on the decklist and my own starter deck says that it contains forbidden cards despite only including 30 lvl 0 surivor, spirit, and neutral cards.

Not sure if you'll be able to view it, but here's my deck: https://arkhamdb.com/deck/view/136757

I believe this is a general issue though, not just something with my deck.

![ahdb error](https://user-images.githubusercontent.com/39221880/39959756-944b3c92-55e4-11e8-814b-7d2493ee5fed.JPG)

EDIT: Okay, so I just noticed that this is likely because there are some FA cards in this deck, but that being said, the note saying that there are forbidden cards in the deck seems to appear no matter what configuration of cards you use to make a Calvin deck.

**Comment by Kamalisk** [comment]
his special card wasnt tagged correctly. It should all be working by now.
