### ISSUE TITLE
deck/new JPGs for new investigators not working

### ISSUE THREAD

**Issue by iamdeveloperidevelop** [Kamalisk/arkhamdb#168]
On card browser new cards in format jpg are working ok. But not on deck/new.  https://arkhamdb.com/deck/new 
Older investigators are in format png that's why they are there, but it gets error during downloading TFA ones.

Copy of my talk from discord:

GET https://arkhamdb.com/bundles/cards/04004.png 500 (Internal Server Error)
5 errors for 5 investigators
TFA:
https://arkhamdb.com/bundles/cards/04002.jpg <--- OK
https://arkhamdb.com/bundles/cards/04002.png <--- 404
PtC:
https://arkhamdb.com/bundles/cards/03002.jpg <--- 404
https://arkhamdb.com/bundles/cards/03002.png <--- OK(edited)
one works, second not. Bug on page :wink: there are no png files for TFA investigators, while only JPG. Thou here: https://arkhamdb.com/cycle/dwl we are looking for png for old ones and new ones jpg https://arkhamdb.com/cycle/tfa while hover over the names for icons (why? not sure, gotta have to create issue on github I guess)

**Comment by Kamalisk** [comment]
restored the pngs.
