### ISSUE TITLE
Randomly chosen basic weakness for new deck was from unreleased pack.

### ISSUE THREAD

**Issue by sacrelicious2** [Kamalisk/arkhamdb#17]
Attempted to build a new deck, and the randomly chosen weakness was Internal Injury, which is from Dunwich Legacy.  I don't have this pack, as it is unreleased.

I think instead of adding the weakness automatically at the beginning of deck creation, there should be a button to randomly choose one using the sets chosen in the "Sets" filter.

**Comment by Kamalisk** [comment]
I need to add proper collection support similar to lotr where you specify which packs you own and it uses that.

**Comment by sacrelicious2** [comment]
The other issue with determining the basic weakness at the beginning is that it may influence your deck building choices, like adding different cards to help combat it.  In the rules, adding the basic weakness is the last step of deck building for this reason.

**Comment by Kamalisk** [comment]
You can easily change the weakness yourself (and choosing it yourself is the main way to add it in the first place as the chances of which weakness you get depends on how many are playing). The plan is to add a place holder random basic weakness card and the user has to replace it. As it is now, just ignore the weakness in your deck and pick one randomly yourself and exchange it for the one in your deck. 

But I choose the weakness first as it makes most gameplay sense (I am creating the character based around their strengths and weaknesses) and you know it every other time you change your deck, it adds nothing to the game for it to be unknown for the first scenario only. (any weaknesses you earn during the campaign you will always know about before you change your deck)

**Comment by Kamalisk** [comment]
So there is now a placeholder in new decks. You can click a button next to it to replace it with a random basic weakness from your collection (or from the packs selected currently in the deck builder). 
Or you can just leave the placeholder, and you can always manually change the weakness as you wish.
