### ISSUE TITLE
Arcane Research - any idea for this getting to work

### ISSUE THREAD

**Issue by iamdeveloperidevelop** [Kamalisk/arkhamdb#171]
It's more like "is there any plans for implementing this card?" I am getting a bit confused when using it with arkhamdb. When I add upgrade, I am input EXP.
Now I can add one additional XP, but who knows if I am going to get another spell? It is the issue with new MP waiting to get new ones and waiting with that XP there.
Then it comes I am getting spell, so now I had +3XP used 4XP. Ok, no probs.
But on next scenario, I am adding +3XP and I am seeing "available 2XP". So I have to keep track how many spells I've upgraded between each scenario and it is not easy, since you have to get history of every each deck between scenarios, which can grow to a lot of those URLs. 
I know it might be impossible to create with code you have there, but I am curious if you even consider implenting something for it or I ahve to create my own workaround =) Cheers

Probably gonna be same problem with the  Shrewd Analysis but for now, my Ursula havent yet upgraded anything with that.

**Comment by zzorba** [comment]
I have some JS code that does the calculation correctly. It would probably work the same way as Adaptable currently does (it doesn't give you extra XP, just decreases the cost on spells you have).

@Kamalisk I could try to integrate this into the arkhamdb project if you would like. 

I have no idea how to make Shrewd Analysis work, since its also an 'optional' trigger -- seems like you would need some UI that assigned random upgrades.

```
function calculateSpentXp(cards, slots, changedCards, exiledCards) {
  const exiledSlots = [];
  forEach(keys(exiledCards), code => {
    if (exiledCards[code] > 0) {
      const card = cards[code];
      forEach(range(0, exiledCards[code]), () => exiledSlots.push(card));
    }
  });
  let adaptableUses = (slots[ADAPTABLE_CODE] || 0) * 2;
  let arcaneResearchUses = (slots[ARCANE_RESEARCH_CODE] || 0);

  const addedCards = [];
  const removedCards = [];
  forEach(keys(changedCards), code => {
    const card = cards[code];
    if (changedCards[code] < 0) {
      for (let i = changedCards[code]; i < 0; i++) {
        removedCards.push(card);
      }
    } else {
      for (let i = 0; i < changedCards[code]; i++) {
        addedCards.push(card);
        if (card.code === ARCANE_RESEARCH_CODE) {
          // Per FAQ, you do not get the arcane research bonus if you just
          // added this card to your deck.
          arcaneResearchUses--;
        }
      }
    }
  });

  return sum(map(
    sortBy(
      // null cards are story assets, so putting them in is free.
      filter(addedCards, card => card.xp !== null),
      card => -card.xp
    ),
    addedCard => {
      // We visit cards from high XP to low XP, so if there's 0 XP card,
      if (addedCard.xp === 0) {
        // We've found matches for all the other cards already.
        // Only 0 XP cards are left, so it's safe to apply adaptable changes.
        if (exiledSlots.length > 0) {
          // Every exiled card gives you one free '0' cost insert.
          pullAt(exiledSlots, [0]);
          return 0;
        }
        // You can use adaptable to swap in to level 0s.
        // It is okay even if you just took adaptable this time.
        if (adaptableUses > 0) {
          for (let i = 0; i < removedCards.length; i++) {
            const removedCard = removedCards[i];
            if (removedCard.xp !== null && removedCard.xp === 0) {
              pullAt(removedCards, [i]);
              adaptableUses--;
              return 0;
            }
          }
          // Couldn't find a 0 cost card to remove, it's weird that you
          // chose to take away an XP card?
          return 1;
        }
        // But if there's no slots it costs you a minimum of 1 xp to swap
        // 0 for 0.
        return 1;
      }

      // XP higher than 0.
      // See if there's a lower version card that counts as an upgrade.
      // TODO(daniel): handle card 04106 (Shrewd Analysis)
      for (let i = 0; i < removedCards.length; i++) {
        const removedCard = removedCards[i];
        if (addedCard.name === removedCard.name &&
            addedCard.xp > removedCard.xp) {

          pullAt(removedCards, [i]);

          // If you have unspent uses of arcaneResearchUses,
          // and its a spell, you get a 1 XP discount on upgrade of
          // a spell to a spell.
          if (arcaneResearchUses > 0 &&
            removedCard.traits_normalized.indexOf('#spell#') !== -1 &&
            addedCard.traits_normalized.indexOf('#spell#') !== -1) {
            let xpCost = (addedCard.xp - removedCard.xp);
            while (xpCost > 0 && arcaneResearchUses > 0) {
              xpCost--;
              arcaneResearchUses--;
            }
            return xpCost;
          }
          // Upgrade of the same name, so you only pay the delta.
          return (addedCard.xp - removedCard.xp);
        }
      }
      return addedCard.xp;
    }
  ));
}
```

**Comment by Kamalisk** [comment]
the best generic idea would just to add a special xp section, where you can add or subtract additional costs. e.g. if you get a cheaper upgrade, then just put the "free" xp in this box and it takes it into account when showing the xp values. 

Anything else might get quite messy, as having to specify if you are upgrading a card or not as you change the deck, would just make deck building clunky.

**Comment by zzorba** [comment]
Good point, it also covers some of the stuff around spending XP for other things besides cards (as they've started doing in the newest campaign).  I've been struggling to capture how to handle that one.

**Comment by zzorba** [comment]
@Sarseth looks like the Arcane Research support has been deployed. 

A more generic solution would be nice as FFG continues iterating on cards that influence deck building, but for now Arcane Research is supported like Adaptable.

**Comment by Kamalisk** [comment]
added a manual xp adjustment for various cards, will still add support for cards if we can.
