### ISSUE TITLE
Never got the registration email button doesn't work + No email to verify account

### ISSUE THREAD

**Issue by LeftyFlip** [Kamalisk/arkhamdb#177]
Just registered for an account today on the website. Said to verify my email through and email sent by the site. I never got it. Then found the button that says Never got the registration email? I click it and it loops back to the login page. Please help + fix

**Comment by LeftyFlip** [comment]
Also registered an account on this website soon after finding support and got the verification email instantly.

**Comment by Kamalisk** [comment]
hotmail addresses have issues (MS keep blocking the sending of mail, and I keep telling them to unblock it). Your account should work now.
