### ISSUE TITLE
Shortcut to link to specific sections of rules

### ISSUE THREAD

**Issue by sacrelicious2** [Kamalisk/arkhamdb#18]
Similar to how we can use '#' to link to specific cards in descriptions, reviews and comments, it would be nice if we use another shorthand for linking to specific sections of the Rules Reference Guide.

As an added benefit, it would be nice if, when hovering on the link, it would give a preview of that section.

**Comment by mplain** [comment]
You can use the Table of Contents on the Rules page, and it'll give you a link to any rules entry you want. Then you can use the standard [text](link) format in the review or comment.

**Comment by sacrelicious2** [comment]
I'm aware of that and have done it.  It would just be nice if there was a shorthand for it.

**Comment by Kamalisk** [comment]
Yeah, he wants an automatic link like when you use icons or card names. It is possible to do but would require some effort and some decision as to what character would initiate the rules shortcut, mixing it in with the cards seems bad, as does the icons, so @,# and $ are taken. ~ ^ { ? Should be something people dont use much so it isnt annoying.

**Comment by Kamalisk** [comment]
I have now added ^ as a shorthand for rules sections, it auto completes based on a section list from the rules pages on arkhamdb and will create an automatic link to it.

**Comment by Kamalisk** [comment]
only took 2 years :P
