### ISSUE TITLE
API: add `Access-Control-Allow-Origin` to the response header for GET https://arkhamdb.com/api/public/cards

### ISSUE THREAD

**Issue by junqdu** [Kamalisk/arkhamdb#180]
something similar to https://netrunnerdb.com/api/2.0/public/cards, so it can be access by other web app. I am working on a clone of https://codepen.io/Theavon/full/YQmgBG for Arkham Horror. Thanks.

**Comment by profwacko** [comment]
Also encountering this issue when trying to pull cards with the API with a simple `js` script running in the browser. Not able to get data.
