### ISSUE TITLE
Problem change language on IOS

### ISSUE THREAD

**Issue by Cheese383** [Kamalisk/arkhamdb#182]
With my iPhone on IOS 10 with Chrome and Safari I cannot change language when I click on the flag

**Comment by Flagrato** [comment]
Also on iOS 11 on iPad and iPhone on Safari and Icab Mobile.

**Comment by Kamalisk** [comment]
changing the language just changes to a different subdomain, so at least for now you can just enter that url manually. e.g. for spanish go to es.arkhamdb.com (or  de, fr, it )

**Comment by Cheese383** [comment]
Ok ! Thank you :)
