### ISSUE TITLE
Norman WIthers No Seeker EXP cards shown

### ISSUE THREAD

**Issue by ElixisJade** [Kamalisk/arkhamdb#184]
When you have selected Norman Withers as your investigator, it does not show you any Seeker cards that cost xp when you select that option. It only shows neutral cards that require exp.

**Comment by zzorba** [comment]
Norman can only take Level 0 Seeker cards according to his deck building rules, he's an odd investigator.

**Comment by Kamalisk** [comment]
working as intended
