### ISSUE TITLE
Figure out how API changes for 'duel' faction cards will work

### ISSUE THREAD

**Issue by zzorba** [Kamalisk/arkhamdb#186]
The latest FFG preview https://www.fantasyflightgames.com/en/news/2018/11/2/the-secret-name/ has new 'dual' faction cards.  Their deck building is a bit weird:

1) if you can take either of the classes they are allowed
2) BUT if you have a limit (Dunwich investigators, Finn, Carolyn, Marie), they will also count against that limit.  

Seems like an API change will be needed to support the duel classes, maybe faction_code becomes an array or we make a new faction of type 'duel' and add a new field to capture the multi_faction?

**Comment by zzorba** [comment]
Correction on the above which complicates the current encoding.

1) Carolyn/Finn/Marie do NOT have dual class cards that match a trait count towards their 5/15 card limits.  
2) Dunwich investigators DO, as does Lola.

Right now these are encoded in the same way -- it seems like maybe a new flag on the Dunwich investigators is the right way to go, as its the more restricted option?

**Comment by Kamalisk** [comment]
Most likely they will be a dual faciton, with an additional field for the factions.
Regarding deck building rules, if there is a limit imposed anywhere then these dual faction cards will apply to it. (so if there is a "heal" horror card that is seeker it will count against her seeker limit)
The best solution will be to essentially run each card over the restrictions twice to take into account the limit (essentially once with each faction, or at least duplicate the faction check twice)

**Comment by zzorba** [comment]
Got it, so a new 'dual' faction with a field to disambiguate it -- that makes sense.

For Carolyn the weird thing is I don't think a 'heal' horror card should count against her limit (the current FAQ from Matt on ArkhamDB says it doesn't count as one of her seeker cards if it applies to the other restrictions).  I guess we'll need to see what comes down in the official clarifications.  

It sounds like for the Dunwich investigators (and maybe Norman) are the exception.

I'm happy to pitch in on any code on ArkhamDB if you'd like.

**Comment by Kamalisk** [comment]
well it had better not be an exception! because then they failed, since it is written the same way. 
The dual cards are already a terrible idea anyway.

**Comment by zzorba** [comment]
Agreed, what a chore of a feature.

The discussion on discord was it might come down to the word “other cards”. Carolyn, Finn, Marie all say 5/15 other cards, so it it applies to a previous rule it doesn’t count (this is made worse by the fact that they 'forgot' to put the word 'Other' on Carolyn).  The current ruling on Carolyn (that a card that 'heals horror', like st hubert's key, doesn't count towards her 15 mystic cards seems to back this up).  

But the dunwich investigators don’t say other, so any off-faction card counts against the limit of 5.  Same for Norman, who just has a general restriction of '5 level 0 mystic cards'?

I'm still holding out hope that they just rule against the blog post, and make them count as whichever faction you want them to for the purpose of deck building.  That's both the most explainable AND intuitive ruling.

**Comment by zzorba** [comment]
Per Matt: 
`re: dual-class cards: The article may or may not be correct. They're working on a faq update that will drop before the dual-class cards are available that should make answer all questions.`

Let's hope the article turns out to be wrong and this becomes a lot easier to deal with.
