### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by sacrelicious2** [Kamalisk/arkhamdb#19]
Site needs a favicon.  Would suggest using an Elder Sign from the chaos token.

**Comment by mattsigal** [comment]
Not my forte, but I took an Elder Sign image from the RRG, removed the background, and converted it into a favicon. Maybe good enough for a placeholder?

Here's a link to the ico: http://www.favicon-generator.org/download/2016-12-08/fff4021320b80c05eb14108c81e67421.ico

And here is the original image I used (in case cleaning it up would improve the icon): 

![eldersign](https://cloud.githubusercontent.com/assets/1421758/21013851/82153d7a-bd29-11e6-8cd0-f7cf708b3ecc.png)

**Comment by Kamalisk** [comment]
thanks. updated the site with the icon now.
