### ISSUE TITLE
X packs required link on iPad

### ISSUE THREAD

**Issue by corbsforce** [Kamalisk/arkhamdb#196]
On an iPad in Chrome browser (maybe other devices and browsers) selecting the “x packs required” link on a deck page doesn’t display any details. It’s probably a ‘hover’ link on a full browser. Can this be enabled to react to a touch?

**Comment by Telon84** [comment]
Same goes for Safari and Chrome on an iPhone.

**Comment by Kamalisk** [comment]
clicking the link should show the packs now
