### ISSUE TITLE
API requests in other languages

### ISSUE THREAD

**Issue by jferranm** [Kamalisk/arkhamdb#199]
I only get results in English on API requests. For example using the subdomain "es": 

https://es.arkhamdb.com/api/public/card/01020

The result appears with the texts in English instead of in Spanish. Is this the right way to use the API?

**Comment by dinomaster13** [comment]
I don't see anything about language in the API doc (https://arkhamdb.com/api/)

**Comment by Kamalisk** [comment]
I fixed it for the single cards now. It was working for all cards but was not working when requesting a specifc card
