### ISSUE TITLE
Card name doesn't link to card page on Reviews page.

### ISSUE THREAD

**Issue by sacrelicious2** [Kamalisk/arkhamdb#20]
The card name above each review on the Reviews page doesn't link back to the card page.  Hovering the link does properly show a card preview, but clicking on it doesn't do anything.  Tested on Chrome.

**Comment by sacrelicious2** [comment]
Interesting to note that if I Right-Click and choose "Open link in new tab", it works fine.

**Comment by Kamalisk** [comment]
link should work now.
