### ISSUE TITLE
Local install

### ISSUE THREAD

**Issue by dinomaster13** [Kamalisk/arkhamdb#202]
I don't know how to import data into mysql, someone could help me ?

**Comment by zzorba** [comment]
Once you have a MySql server running, use these commands.
```
php app/console doctrine:database:create
php app/console doctrine:schema:create
php app/console  app:import:std ../arkhamdb-json-data/
```

Make sure to clone the arkhamdb-json-data project as well.

You might need the fix from https://github.com/Kamalisk/arkhamdb/pull/195 to make the import not OOM

**Comment by dinomaster13** [comment]
Thank you it works perfectly :)

Now i'm blocked in the last step.

I start the server with the command php app/console server:run
=> server running on 127.0.0.1:8000
But i got the message "Arkhamdb is down for maintenance" in firefox ...

**Comment by dinomaster13** [comment]
It ok, i put "website_url: 127.0.0.1" in app/config/parameters.yml

**Comment by zzorba** [comment]
Yeah, I think there’s a maintenance file you just have to delete. Search
for the error message

**Comment by dinomaster13** [comment]
Thank it's work, i have another probleme but i have done another issue
