### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by dinomaster13** [Kamalisk/arkhamdb#204]
It's work fine in english.
I use commande "php app/console  app:import:trans ../arkhamdb-json-data/"
1) It seems to work, but when i try to select spanish, impossible to connect to "http://es.127.0.0.1:8000/"
2) It doesn't import french translation, how to do that ?
3) Where can i found image ?

**Comment by Kamalisk** [comment]
the subdomains require configuration of your webserver. The simpler solution is to set the default language to be "es" in the config rather than trying to set up local subdomains.
Importing french works the same as the other languages.
Images will not be distributed by me outside of the website.
