### ISSUE TITLE
Save error (blank screen and don't save)

### ISSUE THREAD

**Issue by jmt974** [Kamalisk/arkhamdb#205]
Hi

When I try to save my Deck I got a blank screen. Nothing is saved concerning cards in the deck, but a new version is created...

Any idea ?

**Comment by jmt974** [comment]
Additional note : bug only seems to appear when I choose French langage.

**Comment by jferranm** [comment]
Same problem in spanish (HTTP ERROR 500)

**Comment by FriendoftheStomach** [comment]
I have experienced this error (HTTP ERROR 500) using Chrome with English language. Notably, I did not experience this error using Internet Explorer. I attempted to solve this issue in Chrome by refresh the app data as well as clearing my cache of arkhamdb.com stuff and neither method solved the problem. I'll be using IE for the time being.

**Comment by jmt974** [comment]
If it's help I'm using Safari on Mac (tried with chrome, same error...  no IE here :) )

**Comment by Kamalisk** [comment]
clearing the cache should solve this issue, especially if you get it on one subdomain and not on the others.

**Comment by jmt974** [comment]
It seems to works ! Big Thank you :)
