### ISSUE TITLE
Overgrown Cairns incorrectly noted as having Victory 1

### ISSUE THREAD

**Issue by JMSears** [Kamalisk/arkhamdb#207]
Overgrown Cairns (81018) comes up as having Victory 1 in search and in the card spoiler when the card has no mention of it. https://arkhamdb.com/card/81018
![image](https://user-images.githubusercontent.com/47614623/52749934-b3e30b80-2fb8-11e9-9a8c-3ffcabc37945.png)

Great job on this system! Amazing work!

**Comment by zzorba** [comment]
Thanks for the bug report, opened a PR to address this: https://github.com/Kamalisk/arkhamdb-json-data/pull/437
