### ISSUE TITLE
The Circle Undone: Scenario 1 - The Witching Hour - Intro 2

### ISSUE THREAD

**Issue by KoenVal** [Kamalisk/arkhamdb#208]
Intro 2 in the first scenario of The Circle Undone (The Witching Hour), grants you the 'The Tower XVI' & 'Ace of Rods'. ArkhamDB registers those as extra cards for which extra XP is needed (Ace of Rods) resulting in the "Contains too many cards" error and the use of too much XP.
Could these be added under 'Special - Campaign' to bypass this?

**Comment by Kamalisk** [comment]
you can open the popup for a card during deck building to set the deck ignore limit for a card. this lets you indicate it doesnt take up a deck slot.
