### ISSUE TITLE
The boxes to select 1 or 2 under “quantity “ are missing

### ISSUE THREAD

**Issue by wilhelm2264** [Kamalisk/arkhamdb#209]
I can not edit my decks currently on my IPad as the boxes to Check under the quantity section are currently missing.

**Comment by Kamalisk** [comment]
I dont have an ipad but I dont see why they would be specfically missing, have you reloaded? When did they vanish?

**Comment by wilhelm2264** [comment]
Noticed last night. The site works for my iPhone but for my iPad the boxes below quantity are missing, even highlighting that section does nothing. Only thing I can currently think is something changed on my iPad after the lasted update.


Sent from Yahoo Mail for iPad


On Wednesday, February 27, 2019, 12:41 PM, Allan Clements <notifications@github.com> wrote:


I dont have an ipad but I dont see why they would be specfically missing, have you reloaded? When did they vanish?
