### ISSUE TITLE
Upgrade history not shown for published decks

### ISSUE THREAD

**Issue by sacrelicious2** [Kamalisk/arkhamdb#21]
When publishing a deck that has been upgraded, the upgrade history is not shown.  This is information that would be useful when attempting to share decks built for friends.

**Comment by Kamalisk** [comment]
Currently you can only publish the deck itself, so when you do so the link to the previous deck is lost. I plan to let you publish deck sets which means it will include all previous versions of the deck.

**Comment by Kamalisk** [comment]
I believe upgrades are published too.
