### ISSUE TITLE
[Feature Request] Search for cards by investigator access

### ISSUE THREAD

**Issue by andrewshen123** [Kamalisk/arkhamdb#212]
Is it possible to add a search tag that filters the results to only cards that a particular investigator can take? For example, something like "p<3 inv:Preston" would find all Rogue (0-2), Survivor (0-2), Neutral (0-2), but filter out Illicit cards. I imagine there's already similar code for the deckbuilding page, so hopefully it wouldn't require too much to implement.

**Comment by Christopher-Willis** [comment]
Indeed, often I don't really care what cards exist but what cards I can use. A search by investigator would be soooo handy.

**Comment by Kamalisk** [comment]
I have added support for this (aside from Carolyn currently). can search for do: followed by the investigator card code to see all cards they can use.
e.g. 
https://arkhamdb.com/find?q=do%3A04005
