### ISSUE TITLE
After adding a Tarot card all other cards automatically get starred (don't count towards deck size)

### ISSUE THREAD

**Issue by LeonardQuirm** [Kamalisk/arkhamdb#216]
Using Chrome 72.0.3626.121 I found the following behaviour when trying to build a Preston deck:

Adding cards worked normally until I tried adding a Tarot card (Ace of Rods), after which all cards added to the deck got given a Star and didn't count towards my deck limit - and since other cards do not have a "Ignore limit" button toggle, I couldn't change this.

This was reproducible using the steps below.  Note that I add cards in the following way, which may be a key part:
- Choose cards by typing some/all of the name in the text box, then either selecting the entry with the keyboard and hitting enter or clicking on the option in the dropdown.
- Pressing the number on the keyboard for how many copies I want.

With this method, I saw the following behaviour:
- Create new deck
- Add non-Tarot cards as above.  They add normally.
- Add a copy of Ace of Rods as above.  It defaults to being starred.
- Click on Ace of Rods to go back to its page, then click the 0 for "Ignore Limit" to remove the star.  This works as expected.
- Add further cards.  All further cards added are starred, even though they don't have an ignore limit option.

**Comment by Kamalisk** [comment]
thanks for finding this. Using the number keys was causing the issue. fixed now (do a refresh if you still see the issue)
