### ISSUE TITLE
Cannot search for vengeance cards

### ISSUE THREAD

**Issue by bahafeli** [Kamalisk/arkhamdb#217]
Searching text for "vengeance" does not find cards with a Vengeance value.

**Comment by Danielh21** [comment]
I think you just need to adjust your search a bit to include encounter cards as well.

Like this:

https://arkhamdb.com/find?q=x%3Avengeance&sort=name&view=list&decks=encounter&spoilers=hide

**Comment by Kamalisk** [comment]
the search above seems to work fine. By default the advanced search only looks at player cards. (I might change that) but vengeance search seems ok.
