### ISSUE TITLE
Add Campaign Guide

### ISSUE THREAD

**Issue by sacrelicious2** [Kamalisk/arkhamdb#22]
It would be nice if we had the campaign guide for current and future scenarios available on the site, in a format similar to the Rules page.

**Comment by Kamalisk** [comment]
As I said on reddit, this has been done by mplain and I am just unsure I want to publish it.

**Comment by jon-adams** [comment]
@Kamalisk I concur that the campaign guide should _not_ be published. That's the bit that FFG cares more about regarding copyright and such.
