### ISSUE TITLE
Unable to post card review

### ISSUE THREAD

**Issue by dharlette** [Kamalisk/arkhamdb#221]
I attempted to post the following review for The Necronomicon (Olaus Wyrmius Translation), and received an error message.

**Attempted text**
```**Amazing for Daisy, awful for everyone else**

You know how [Dr. Milan Christopher](/card/01033) is an amazing card, one that you essentially want to get out IMMEDIATELY in any seeker deck? Well, if you're [Daisy Walker](/card/01002), this is basically another copy of [Dr. Milan Christopher](/card/01033) in your deck, except it counts as a tome and thereby improves your eldritch sign ability instead of taking up an ally slot.  [The Necronomicon](/card/02140) shouldn't be thought of as a replacement for the good doctor so much as as an additional copy. If you hard-mulligan for Dr. Christopher, you have a 55% chance of drawing him in your opening hand in a 31 card deck. Adding in The Necronomicon vaults the chances of drawing one of those three cards in your now 32-card deck up to 69%! {nice} The card pays for itself first turn, costing you 1 action and a hand slot for a permanent assurance of never running out of resources.

Given the utility of [Higher Education](/card/02187), having *some* sort of resource-drawing engine in play is critical for Daisy.   While it's no replacement for [Dr. Milan Christopher](/card/01033), it dramatically increases your chance of survival. And if you have **both** out, you can pull a whopping 6 resources/turn for the cost of...a free action. Encourage your partners to run [Teamwork](/card/02018) so you can share the bounty, and watch as resource intensive cards like [Streetwise](/card/02189) and [Keen Eye](/card/02185) suddenly become a lot more valuable.

If you're not Daisy, then this card becomes *terrible*. It takes an action to put in play, and an action to use. The first use just covers its cost to play, so you're down 2 actions for no gain. The second use gets you two resources, but you could have just gained two resources instead of playing & using it, so you're still down a net one resource. You have to use *five actions* to have more resources than someone who just used the last four actions to gather resources! Alternatively, it's an action and 2 resources for a +1 into boost, which is pretty crap compared to just playing a [Magnifying Glass](/card/01030).

Compare:
Player using the Necronomicon
* Character starts with 2 resources
* Action 1: Plays Necronomicon, down to 0
* Action 2: uses Necronomicon, back to 2 resources
* Action 3: uses Necronomicon, up to 4 resources
* Action 4: uses Necronomicon, up to 6 
* Action 5: uses Necronomicon, up to 8

Player without the Necronomicon
* Character starts with 2 resources
* Action 1: gains 1 resource, up to 3
* Action 2: gains 1 resource, up to 4
* Action 3: gains 1 resource, up to 5
* Action 4: gains 1 resource, up to 6
* Action 5: gains 1 resource, up to 7
```

After hitting "Submit review", I received the following error message:

> `An exception occurred while executing 'INSERT INTO review (date_creation, date_update, text_md, text_html, nb_votes, is_faq, card_id, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params ["2019-05-14 02:44:40", "2019-05-14 02:44:40", "**Amazing for Daisy, awful for everyone else**\r\n\r\nYou know how [Dr. Milan Christopher](\/card\/01033) is an amazing card, one that you essentially want to get out IMMEDIATELY in any seeker deck? Well, if you're [Daisy Walker](\/card\/01002), this is basically another copy of [Dr. Milan Christopher](\/card\/01033) in your deck, except it counts as a tome and thereby improves your eldritch sign ability instead of taking up an ally slot. [The Necronomicon](\/card\/02140) shouldn't be thought of as a replacement for the good doctor so much as as an additional copy. If you hard-mulligan for Dr. Christopher, you have a 55% chance of drawing him in your opening hand in a 31 card deck. Adding in The Necronomicon vaults the chances of drawing one of those three cards in your now 32-card deck up to 69%! {nice} The card pays for itself first turn, costing you 1 action and a hand slot for a permanent assurance of never running out of resources.\r\n\r\nGiven the utility of [Higher Education](\/card\/02187), having *some* sort of resource-drawing engine in play is critical for Daisy. While it's no replacement for [Dr. Milan Christopher](\/card\/01033), it dramatically increases your chance of survival. And if you have **both** out, you can pull a whopping 6 resources\/turn for the cost of...a free action. Encourage your partners to run [Teamwork](\/card\/02018) so you can share the bounty, and watch as resource intensive cards like [Streetwise](\/card\/02189) and [Keen Eye](\/card\/02185) suddenly become a lot more valuable.\r\n\r\nIf you're not Daisy, then this card becomes *terrible*. It takes an action to put in play, and an action to use. The first use just covers its cost to play, so you're down 2 actions for no gain. The second use gets you two resources, but you could have just gained two resources instead of playing & using it, so you're still down a net one resource. You have to use *five actions* to have more resources than someone who just used the last four actions to gather resources! Alternatively, it's an action and 2 resources for a +1 into boost, which is pretty crap compared to just playing a [Magnifying Glass](\/card\/01030).\r\n\r\nCompare:\r\nPlayer using the Necronomicon\r\n* Character starts with 2 resources\r\n* Action 1: Plays Necronomicon, down to 0\r\n* Action 2: uses Necronomicon, back to 2 resources\r\n* Action 3: uses Necronomicon, up to 4 resources\r\n* Action 4: uses Necronomicon, up to 6 \r\n* Action 5: uses Necronomicon, up to 8\r\n\r\nPlayer without the Necronomicon\r\n* Character starts with 2 resources\r\n* Action 1: gains 1 resource, up to 3\r\n* Action 2: gains 1 resource, up to 4\r\n* Action 3: gains 1 resource, up to 5\r\n* Action 4: gains 1 resource, up to 6\r\n* Action 5: gains 1 resource, up to 7", "<p><strong>Amazing for Daisy, awful for everyone else<\/strong><\/p>\n<p>You know how <a href=\"\/card\/01033\">Dr. Milan Christopher<\/a> is an amazing card, one that you essentially want to get out IMMEDIATELY in any seeker deck? Well, if you're <a href=\"\/card\/01002\">Daisy Walker<\/a>, this is basically another copy of <a href=\"\/card\/01033\">Dr. Milan Christopher<\/a> in your deck, except it counts as a tome and thereby improves your eldritch sign ability instead of taking up an ally slot. <a href=\"\/card\/02140\">The Necronomicon<\/a> shouldn't be thought of as a replacement for the good doctor so much as as an additional copy. If you hard-mulligan for Dr. Christopher, you have a 55% chance of drawing him in your opening hand in a 31 card deck. Adding in The Necronomicon vaults the chances of drawing one of those three cards in your now 32-card deck up to 69%! {nice} The card pays for itself first turn, costing you 1 action and a hand slot for a permanent assurance of never running out of resources.<\/p>\n<p>Given the utility of <a href=\"\/card\/02187\">Higher Education<\/a>, having <em>some<\/em> sort of resource-drawing engine in play is critical for Daisy. While it's no replacement for <a href=\"\/card\/01033\">Dr. Milan Christopher<\/a>, it dramatically increases your chance of survival. And if you have <strong>both<\/strong> out, you can pull a whopping 6 resources\/turn for the cost of...a free action. Encourage your partners to run <a href=\"\/card\/02018\">Teamwork<\/a> so you can share the bounty, and watch as resource intensive cards like <a href=\"\/card\/02189\">Streetwise<\/a> and <a href=\"\/card\/02185\">Keen Eye<\/a> suddenly become a lot more valuable.<\/p>\n<p>If you're not Daisy, then this card becomes <em>terrible<\/em>. It takes an action to put in play, and an action to use. The first use just covers its cost to play, so you're down 2 actions for no gain. The second use gets you two resources, but you could have just gained two resources instead of playing &amp; using it, so you're still down a net one resource. You have to use <em>five actions<\/em> to have more resources than someone who just used the last four actions to gather resources! Alternatively, it's an action and 2 resources for a +1 into boost, which is pretty crap compared to just playing a <a href=\"\/card\/01030\">Magnifying Glass<\/a>.<\/p>\n<p>Compare:\nPlayer using the Necronomicon<\/p>\n<ul><li>Character starts with 2 resources<\/li>\n<li>Action 1: Plays Necronomicon, down to 0<\/li>\n<li>Action 2: uses Necronomicon, back to 2 resources<\/li>\n<li>Action 3: uses Necronomicon, up to 4 resources<\/li>\n<li>Action 4: uses Necronomicon, up to 6 <\/li>\n<li>Action 5: uses Necronomicon, up to 8<\/li>\n<\/ul><p>Player without the Necronomicon<\/p>\n<ul><li>Character starts with 2 resources<\/li>\n<li>Action 1: gains 1 resource, up to 3<\/li>\n<li>Action 2: gains 1 resource, up to 4<\/li>\n<li>Action 3: gains 1 resource, up to 5<\/li>\n<li>Action 4: gains 1 resource, up to 6<\/li>\n<li>Action 5: gains 1 resource, up to 7<\/li>\n<\/ul>", 0, 0, 416, 19385]: SQLSTATE[HY000]: General error: 1364 Field 'is_question' doesn't have a default value `

**Comment by Kamalisk** [comment]
thanks for reporting it. should be fixed now.
