### ISSUE TITLE
Back image not showing for card "Into the Beyond"

### ISSUE THREAD

**Issue by Shawnecy** [Kamalisk/arkhamdb#222]
This is at https://arkhamdb.com/card/02317

I don't see any issues with the card's data or the image import logic so unsure of the cause.

Here's information if the image just needs to be restored to some static content folder:

Card name: Into the Beyond
Cycle: The Dunwich Legacy
Mythos Pack: Lost in Time and Space
FFG product code: AHC08
Card position: 317
FFG Image URL: http://lcg-cdn.fantasyflightgames.com/ahlcg/AHC08_317b.jpg

**Comment by Kamalisk** [comment]
usually is something to do with how it is stored on cgdb, added it manually.
