### ISSUE TITLE
"You owe me one!" not showing in card list in deck builder

### ISSUE THREAD

**Issue by canyouflybobbi** [Kamalisk/arkhamdb#231]
"You owe me one!" is not showing in the card list in the deck builder (I've tried Skids and Finn), if you type it in the card filter and select it from the pop-up it goes in your deck but does not count towards deck size:

![image](https://user-images.githubusercontent.com/52250562/61994107-3bf03580-b06e-11e9-9186-ef196306b47c.png)

**Comment by zzorba** [comment]
I believe this has been fixed, the XP accidentally was left off of it initially.

**Comment by canyouflybobbi** [comment]
Yep it seemed to be working yesterday thanks :)
