### ISSUE TITLE
Carolyn Fern cannot select certain neutral items

### ISSUE THREAD

**Issue by Thakaris** [Kamalisk/arkhamdb#238]
Hi,

first of all, thanks for your great job coding all this, it is an amazing peace of work. Having said that, I would like to report a potential bug:
Carolyn Ferns deckbuilding options read as follows
Deckbuilding Options: Guardian cards level 0-3, Neutral cards level 0-5, cards that "heal horror" level 0-5, up to 15 other Seeker and/or Mystic cards level 0-1
But when I want to give Carolyn an Ornate Bow or Timeworn Brand, than both cards are not available within the neutral asset list LV 1-5, if I check "unusable cards" than those cards show up. As far as I understand it, Carolyn should be able to use all neutral cards available in the game.

BR

![Selection_054](https://user-images.githubusercontent.com/54948429/64353555-3cc99f00-cffe-11e9-99d4-bb293da640a1.png)

**Comment by zzorba** [comment]
She has an additional restriction that prevents her from taking weapons that are not level 0.
`Additional Restrictions: No Weapon cards level 1-5.`

**Comment by Thakaris** [comment]
mmh, reading things completely is definitely helpful.
Thanks a lot and sorry for bothering

BR
