### ISSUE TITLE
Cannot use API: SSL Certificate for arkhamdb.com uses TLS 1.0

### ISSUE THREAD

**Issue by hardingalexh** [Kamalisk/arkhamdb#243]
Hello,

I am trying to use the Arkhamdb API to grab cards for a discord bot (being able to reference a card in chat). It looks like the SSL certificate that ArkhamDB uses is still using TLS1.0, which is long since deprecated. Most modern versions of OpenSSL don't support it anymore, so regardless of what method I use to send a get request (`requests` in python, `node-fetch` and `axios` in js), I get SSL errors based on this. 

For example, from requests:

```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.arkhamdb.com', port=443): Max retries exceeded with url: /api/public/cards (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:852)'),))
```

Is there any way that you can update the SSL certificate to use a newer TLS version, or do you have any examples of API use that get around this limitation in python/php/js?

**Comment by Kamalisk** [comment]
Thanks, I kept forgetting to do that, disabled those now.

I presume you can just tell it to ignore invalid certs which probably covers tls 1.0 too, though you shouldnt need to anymore :P
