### ISSUE TITLE
Always add a second core box

### ISSUE THREAD

**Issue by Jashugansky** [Kamalisk/arkhamdb#251]
Hello

When I select a 2nd skill card it always add a 2nd core box

Regards

![image](https://user-images.githubusercontent.com/57317097/68084382-fe513480-fe34-11e9-9166-7605637f2662.png)
![image](https://user-images.githubusercontent.com/57317097/68084386-06a96f80-fe35-11e9-9ec7-97a1d41e7f7e.png)

**Comment by Kamalisk** [comment]
corrected it so it only selects the second core set if you add multiple of the one-ofs from the core set.
Make sure to refresh the page properly if you still see the problem.

**Comment by Jashugansky** [comment]
It seems to work correctly. you're the best :) 

thanks
