### ISSUE TITLE
Switching Tony Morgan's Subclass in a Given Deck Marks the Subclass Cards as Forbidden

### ISSUE THREAD

**Issue by hecateeeee** [Kamalisk/arkhamdb#255]
I had a Tony Morgan deck subclassed as Guardian. I rerolled the deck a bit, but kept it as the same entry in ArkhamDB, this time subclassed as a Seeker. Now all of the Seeker cards are struckthrough and marked as "forbidden."

![imagen](https://user-images.githubusercontent.com/7151453/69444815-c09a4a00-0d16-11ea-8dff-3910cf9cefb6.png)

**Comment by Kamalisk** [comment]
did you change it to a seeker deck?

**Comment by hecateeeee** [comment]
Oh, I see. In that case, switch this from a bug to a feature request for clearer labeling on that.

Thanks for the response!
