### ISSUE TITLE
upgrading tony morgan flags deck as illegal

### ISSUE THREAD

**Issue by stopfstedt** [Kamalisk/arkhamdb#256]
possibly related to #255

to reproduce:

1. take any tony deck and clone it (i started with https://arkhamdb.com/decklist/view/15838/the-bounty-hunter-hunts-for-clues-solo-multiplayer-1.0)
2. upgrade the deck. 
3. observe that your off-class cards (seeker in my case) appear struck-through, indicating deck illegality, and an error message `Contains forbidden cards (cards not permitted by Investigator)` appears in the deck builder.

![Selection_060](https://user-images.githubusercontent.com/1410427/69776810-8d125200-1152-11ea-8b91-ddf14520119c.png)

downgrading the deck will return it to its original/legal state.

**Comment by Kamalisk** [comment]
should be fixed now.

**Comment by stopfstedt** [comment]
confirmed. thanks for the quick fix!
