### ISSUE TITLE
Rules Inquiry Response for Double, Double

### ISSUE THREAD

**Issue by msbeck** [Kamalisk/arkhamdb#258]
> Q. In the Arkham Horror LCG, can you use Double, Double on Scene of the Crime (as Tony)? Can you Double, Double with Evidence?

> A. Yes, you can. You can use Double, Double on Scene of the Crime because it is still technically your first action (the second playing of the card does not cost an action). As for Evidence, it is a reaction to defeating an enemy, so as long as you are still in that same opportunity window (having just defeated the enemy), it is perfectly legal to use Double, Double to play it a second time. In this way, it’s no different from having two copies of Evidence in hand and playing both of them, one at a time.

https://arkhamdb.com/card/05320

Response to rules form question by Matt Newman by email on 2019-12-3

**Comment by drawntotheflame** [comment]
@Kamalisk this can be closed. 

@msbeck please in future email rulings to drawntotheflamepodcast[at]gmail.com so that I can add them to FAQ entries on arkhamdb. Thanks!
