### ISSUE TITLE
Rules Inquiry Response for Carolyn's Ability

### ISSUE THREAD

**Issue by msbeck** [Kamalisk/arkhamdb#259]
> Q. How does Carolyn's ability work with a heal to multiple targets? Using Soothing Mirror to heal your investigator and your partner's investigator yields how many resources for each? If you heal your investigator and your own ally, how much do you get? If you heal a friend and their ally, how much do they get? Essentially, can you get multiple resources out of Carolyn's ability if there are multiple targets/controllers for a single effect? Or is it tied to the effect itself, which was only taken once?

> A. If you heal more than 1 horror from a single card, the controller will only get 1 resource as you are only able to trigger Carolyn’s reaction once. However, if you heal horror from several different cards, even from a single effect, you can trigger Carolyn’s reaction once for each card that was healed. So, for example, if you had a hypothetical card that healed 1 horror from each investigator at a location, you could trigger Carolyn’s reaction once for each of those investigators, granting each of them 1 resource.

> Q. So it looks like the key is the number of different cards healed. The owner of any card which gets healed gets (max) 1 resource per card. So to be entirely explicit about the final case - if Carolyn heals horror from herself and an ally card of hers, she gets 2 resources total, right?

> A. Correct!

https://arkhamdb.com/card/05001

Response to rules form question by Matt Newman by email on 2019-12-3

**Comment by drawntotheflame** [comment]
Added to Carolyn's page.
