### ISSUE TITLE
Extra card with Versatile flagged on Carolyn if Seeker or Mystic

### ISSUE THREAD

**Issue by bahafeli** [Kamalisk/arkhamdb#261]
https://arkhamdb.com/deck/view/549089

On this deck, Carolyn deck I have 15 non-healing Seeker and Mystic cards.  Versatile should let me add a sixteenth, but it flags the deck as  invalid.  Choosing a card from the other three classes does not.

**Comment by Kamalisk** [comment]
assuming that is how it is meant to work, versatile is hopefully fixed not take up other deck option slots.

**Comment by bahafeli** [comment]
This still does not seem to be working.  Not it says that the sixteenth Seeker/Mystic card is forbidden.

Versatile allows you to take an additional card of any class.  I do not believe Carolyn's deck building restricts that card from being a level 0 Seeker or Mystic, as the rule about those cards is not a restriction, unlike the Weapon restriction.

**Comment by Kamalisk** [comment]
did you reload or clear the cache?
