### ISSUE TITLE
Trait search

### ISSUE THREAD

**Issue by KrytenKoro** [Kamalisk/arkhamdb#262]
When I try to do a trait search, it comes back no results.

ex. k:"Ancient One"

This happens every time I use the pulldown menu on the cardsearch main page.

When I try to type it by hand, without quotation marks, I can get results, but only for one-word traits.

In general, I cannot get two-word searches to work.

**Comment by TopRamen33** [comment]
Works now. Issue can be closed.
https://arkhamdb.com/find?q=k%3A%22Ancient+One%22&sort=set&view=card&decks=all&spoilers=hide
