### ISSUE TITLE
Cannot delete a blank tag in My Decks.

### ISSUE THREAD

**Issue by Samurai-Kyo** [Kamalisk/arkhamdb#264]
In the my decks page I created a tag for some decks. Later I created a new tag with the same name. Now I have the normal tag and a blank tag. This blank tag has no name and still points the the decks is was tagged to.

I tried deleting this tag with both the remove one tag and clear all tags options. The tag disappears, but returns upon reloading the my decks page.

It can be seen here between the "seeker" and "Old" tags.
![Blank Tag](https://user-images.githubusercontent.com/46701588/71424793-b8119800-2663-11ea-9d79-e79882237fd8.PNG)

**Comment by Kamalisk** [comment]
blank tag shouldnt appear now.
