### ISSUE TITLE
Versatile (a Thousand Shapes of Horror)

### ISSUE THREAD

**Issue by Thakaris** [Kamalisk/arkhamdb#266]
Hi team,

thank you for the outstanding work on this. I would like to report a bug regarding the new card "Versatile". It happened to be, that when I take that card, the deck size is adjusted accordingly, but I cannot buy level 0 cards at 0 xp, the application charges me in an ongoing champaign, so I asked lead designer Matthew Newmann over at FFG about that, and here is what I have got as a response: 
"We’ll be adding this to the next iteration of the FAQ, but the rule about repurchasing cards when you exile a card and must purchase a new card to maintain your deck size applies here, as well. Essentially, anytime a card effect causes your deck size to be under your investigator’s required deck size, you may purchase new level 0 cards at 0 experience cost to make up for this. This includes both effects that remove cards from your deck (such as when you exile a card), and also effects that increase your deck size."
BR
Uwe

**Comment by Kamalisk** [comment]
it should give you 5 free level 0 cards when you add a versatile now.
