### ISSUE TITLE
[Bug] Adding multiple DIFFERENT myriad XP cards, only costs 1 XP, not 1 per card type.

### ISSUE THREAD

**Issue by halo99** [Kamalisk/arkhamdb#270]
Please see the following decklist which adds both Three Aces and Segments of Onyx in the same upgrade for Mandy.

I believe this should cost 2XP for the 6 cards in total, but only 1 is added.

**Comment by halo99** [comment]
https://arkhamdb.com/deck/view/608978

**Comment by Kamalisk** [comment]
it should work correctly now.
