### ISSUE TITLE
XP calculated one fewer than it should have or my deck 

### ISSUE THREAD

**Issue by Merlin8000** [Kamalisk/arkhamdb#273]
I upgraded my deck here: https://arkhamdb.com/deck/view/602597
to this: https://arkhamdb.com/deck/view/623981

Adding Versatile and a second copy of Ace of Rods (ignore limit 1 due to campaign).  The deckbuilder only shows 2 XP was spent, but the cards add up to 3 XP total.

**Comment by Kamalisk** [comment]
should be fixed now.
