### ISSUE TITLE
Versatile with Mandy Thompson

### ISSUE THREAD

**Issue by ngyq87** [Kamalisk/arkhamdb#274]
1) Rules are that you can take 10 mystic/survivor/rogue(secondary class) event/skill cards with Mandy Thompson's ability PLUS 1 level 0 card of any class from Versatile's ability.

However, it appears that adding certain 1 XP cards in the 11 cards will reproduce the error, the other 10 cards being 0 XP event/skill cards.

Listed 1 XP cards that can reproduce error.

Mystic:
Banish
Stargazing

Rogue:
Three Aces

Survivor:
Brute Force
Expeditious Retreat
Sharp Vision

2) Happens to Tony Morgan too.

Survivor (see above)

Seeker: 
Extensive Research

Guardian:
"Fool me once..."
Well Maintained

**Comment by zzorba** [comment]
I think I could probably make this fix @Kamalisk.  The way I implemented it was having the DeckValidation JS know which rule is "last" with the assumption that only the 'last' rule has a hard limit.  I.E. Versatile becomes the last rule for Mandy, and so her 10 events/skills doesn't error when it hits its limit, it lets it fall through into the Versatile rule.  The assumption here is that the limit will always be the last rule (which right now is true, but who knows what the future holds).

**Comment by Kamalisk** [comment]
So I made it check cards sorted by level descending, which for the most part should work to solve the problem. Most investigators have descending level options, and this makes sure that the level 1 cards are consumed by Mandy's limit, so that versatile only takes the level 0.
