### ISSUE TITLE
Restore option for investigators sorted by class when creating a new layout

### ISSUE THREAD

**Issue by mannerpots** [Kamalisk/arkhamdb#281]
The old layout for choosing an investigator for a new deck, where investigators were sorted by class, is much easier to use than having them sorted alphabetically.
Could you add an option to use the old layout?

**Comment by Kamalisk** [comment]
you can just click to show only that class. Does that not suffice?

**Comment by mannerpots** [comment]
It is very helpful to be able to see the investigators all in one (but sorted), for example when choosing an investigator to play for a campaign.

**Comment by Kamalisk** [comment]
I have added a sort option for the investigator screen now, you can select to sort by class.
You can also now select to sort by investigator stats aswell.
