### ISSUE TITLE
Automatic import of decks misses cards

### ISSUE THREAD

**Issue by idlaviV** [Kamalisk/arkhamdb#282]
Hi,

I just exported a deck from the site in a text file. When I then tried to import the text file via "My Decks->Import Deck" (as file --> Text), some cards got lost. Here is a list of lost cards:
> 1x Strange Solution:Unidentified (The Dunwich Legacy)
> 1x Strange Solution:Acidic Ichor [4] (Where Doom Awaits)
> 1x Analytical Mind:Between the Lines (The Path to Carcosa)
> 1x The King in Yellow:Act 1 (The Path to Carcosa)
> 1x No Stone Unturned [5] (Dim Carcosa)

Notably, most cards contain a ":". The cards are only missing in the imported deck, not in the exported text file.

Also, importing a OCTGN file which was exported before from the database threw the following error:
> The server encountered an error. Please report it to @Kamalisk on Twitter or Reddit.

It would be great to have a reliable way to import/export decks!

**Comment by Kamalisk** [comment]
I have "fixed" it for most cases, I dont know if all cards work, but it should be way more accurate now.
