### ISSUE TITLE
Wrong Picture Dream Gate (06015a)

### ISSUE THREAD

**Issue by owdafeelgreat** [Kamalisk/arkhamdb#285]
Hy there,

I just want to let you know that there is a wrong picture for Dream-Gate (06015a).
There are two pictures of Dream-Gate (Pointless Reality). The upper one must be a picture for Dream-Gate (Wondrous Journey). The text is correct.

Thank you for fixing the problem.

**Comment by TopRamen33** [comment]
This has been fixed and can be closed
https://arkhamdb.com/find?q=06015a&sort=set&view=card&decks=all&spoilers=hide
