### ISSUE TITLE
Rex Can Not Take Lucky

### ISSUE THREAD

**Issue by azgadil** [Kamalisk/arkhamdb#286]
Building a Deck with Rex and I can not take Lucky!  It appears as warning “Forbidden”

**Comment by elkeinkrad** [comment]
Rex cannot take _Lucky!_ card.

[Rex](https://arkhamdb.com/card/02002)'s back card includes...
> **Deckbuilding Restrictions**: No **_Fortune_** cards.

Also, [_Lucky!_](https://arkhamdb.com/card/01080) has **_Fortune_** traits.

**Comment by Kamalisk** [comment]
yep, it is not a valid card for Rex.
