### ISSUE TITLE
Translation question for arkhamdb itself

### ISSUE THREAD

**Issue by elkeinkrad** [Kamalisk/arkhamdb#289]
I know that the placeholder of translation file is in [src/AppBundle/Resources/translations](https://github.com/Kamalisk/arkhamdb/tree/arkham/src/AppBundle/Resources/translations). (xlf file)

But I think that may not be a live version. (korean language is kr, not ko)

I wanna to translate those file. How I can do?

- wait until live version is updated. Then, PR translated one.
- Or, just translate current one.
- Or, another way?

My concern is that since this placeholder contains unique IDs like below, the live placeholder may be necessary.

> \<trans-unit **id="0557fa923dcee4d0f86b1409f5c2167f"** resname="Back"\>

**Comment by Kamalisk** [comment]
for the site itself, I have to generate the translation files with placeholders and then someone can translate those files.

**Comment by elkeinkrad** [comment]
Thanks for your reply.

I wait translation file is updated!

**Comment by Kamalisk** [comment]
took me a while but I finally updated the placeholders at https://github.com/Kamalisk/arkhamdb/tree/arkham/src/AppBundle/Resources/translations

**Comment by elkeinkrad** [comment]
Thanks you. I generated PR #306.
