### ISSUE TITLE
Search page - align Health and Sanity

### ISSUE THREAD

**Issue by mplain** [Kamalisk/arkhamdb#29]
![1](https://cloud.githubusercontent.com/assets/7605827/20831007/337b6f3e-b894-11e6-82f3-2aabd22dc812.png)

**Comment by Kamalisk** [comment]
it is lined up properly for me, what browser do  you use?

**Comment by mplain** [comment]
Google Chrome v 55.0.2883.75 m

**Comment by mattsigal** [comment]
Yup, misaligned here too - on Google Chrome Version 57.0.2939.0 canary (64-bit). But sorting lists is way higher priority ;)

**Comment by Kamalisk** [comment]
Fixed when I next update live.
