### ISSUE TITLE
Ace of Rods and The Tower need Campaign versions

### ISSUE THREAD

**Issue by madantichris** [Kamalisk/arkhamdb#294]
From Page 7 of The Circle Undone rules (Intro 2): 

> Before drawing his or her opening hand for this scenario, the lead investigator searches the collection for 1 copy of The Tower · X V I and 1 copy of Ace of Rods and adds each of them to his or her deck, if able. The lead investigator has earned these cards. They do not count toward his or her deck size. (If one or both of these cards are not available, skip this step.)

Currently, these cards are only available in the UI for normal purchase.  When you attempt to add Ace of Rods to your deck, it still counts against your deck size and charges XP.   There should be a Campaign version of these cards for The Circle Undone.

**Comment by Kamalisk** [comment]
it is not ideal, but if you add ace of rods to your deck, and open the card dialog, there is an option to specify that the card does not count towards your deck size.

**Comment by madantichris** [comment]
> 
> 
> it is not ideal, but if you add ace of rods to your deck, and open the card dialog, there is an option to specify that the card does not count towards your deck size.

Ah, interesting.  I hadn't noticed that option before.  That works.  Thanks!
