### ISSUE TITLE
How do you "make a deck public"?

### ISSUE THREAD

**Issue by nfirvine** [Kamalisk/arkhamdb#296]
https://github.com/Kamalisk/arkhamdb/blob/f316f9d2f1f90b6d99048d832a46b751be9e5514/src/AppBundle/Resources/views/Decklist/decklist_edit.html.twig#L5 says to make your deck "public" not "published" for TTS. I don't know what that means and I can't find any links or pages or buttons that do that.

**Comment by nfirvine** [comment]
Ah, I found it. `Edit Account > Share your decks`. I'd recommend using the same wording in both locations, and a link would be nice.

**Comment by Kamalisk** [comment]
I updated deck pages to show that the deck is private or public with a link of how to change it. Hope that helps people find the option better and to see if their decks are public or not.
