### ISSUE TITLE
"do" search bug in translated DB with trait options

### ISSUE THREAD

**Issue by elkeinkrad** [Kamalisk/arkhamdb#299]
Case about Ursula Downs. However, all investigator with keyword-based deckbuilding option may have same problem.

Her deckbuilding option contains **_relic_** 0-4. Therefore, the two are same.
* non-seeker, non-netural player cards with **_relic_** keyword (level 0-4): `k:relic p<5 f:guardian|mystic|survivor|rogue`
* non-seeker, non-netural player cards Ursula can hold: `do:04002 f:guardian|mystic|survivor|rogue`

Here is serach result in english & korean server.
* [`k:relic p<5 f:guardian|mystic|survivor|rogue`](https://arkhamdb.com/find?q=k%3Arelic+p%3C5+f%3Aguardian%7Cmystic%7Csurvivor%7Crogue&sort=faction&view=list&decks=player&spoilers=hide): 19 cards -- english case. non-seeker|netural relics
* [`do:04002 f:guardian|mystic|survivor|rogue`](https://arkhamdb.com/find?q=do%3A04002+f%3Aguardian%7Cmystic%7Csurvivor%7Crogue&sort=faction&view=list&decks=player&spoilers=hide): 20 cards -- english case. non-seeker|netural cards for Ursula. One difference is for `Scroll of Secrets`, non-relic multi-class card.
* [`k:relic|유물 p<5 f:guardian|mystic|survivor|rogue`](https://ko.arkhamdb.com/find?q=k%3Arelic%7C%EC%9C%A0%EB%AC%BC+p%3C5+f%3Aguardian%7Cmystic%7Csurvivor%7Crogue&sort=faction&view=list&decks=player): 19 cards -- korean case. same as above.
  * note that **_유물_** is the translation for **_relic_**. Since some cards are not translated yet, OR search is necessary.
* [`do:04002 f:guardian|mystic|survivor|rogue`](https://ko.arkhamdb.com/find?q=do%3A04002+f%3Aguardian%7Cmystic%7Csurvivor%7Crogue&sort=faction&view=list&decks=player): 6 cards. -- korean case.

I think, this iss because `do:04002` search try to convert `k:relic p<5` for **_relic_** cards even in translation server.

**Comment by Kamalisk** [comment]
should search the realTrait now instead of the translated text when checking investigator deck options.
