### ISSUE TITLE
Decklist search broken when filtering for particular investigators

### ISSUE THREAD

**Issue by mattsigal** [Kamalisk/arkhamdb#30]
Running the latest Chrome Canary (so might just be my browser), but it appears decklist search is broken if you are trying to filter by the investigator card, rather than a player card.

![screen shot 2016-12-08 at 09 11 44](https://cloud.githubusercontent.com/assets/1421758/21012985/5bfc97d0-bd26-11e6-8bd4-2b8911dfb56e.png)

The investigator card names do show up in the quick fill list as options, so a little weird that they break the search itself.

Also, my browser reports something funny when using this field:

![screen shot 2016-12-08 at 09 13 36](https://cloud.githubusercontent.com/assets/1421758/21013072/a50ac316-bd26-11e6-9459-9db7c3cc2055.png)

Apparently, it is keyed to be a credit card field?

**Comment by Kamalisk** [comment]
I have no idea why chrome does that but switched to https now so I guess it won't complain at least. Search should work again now.

**Comment by mattsigal** [comment]
Haahaha, you are correct that Chrome no longer complains... but now it legit thinks it should be autofilling in credit card information:

![screen shot 2016-12-17 at 08 20 19](https://cloud.githubusercontent.com/assets/1421758/21295393/3501a1ee-c522-11e6-817e-08c0ba66455a.png)
