### ISSUE TITLE
What is 'article' the argument of the command 'php bin/console app:import:images'

### ISSUE THREAD

**Issue by freejerry** [Kamalisk/arkhamdb#307]
I want to collect image files using php 'bin/console app:import:images', but it only download all jpg files but png files.
I found it has the argument 'article' can use to collect png files, but I don't know how to use it.
Is there any suggest for this case?
Thanks.

**Comment by Kamalisk** [comment]
The article is meant to let it download images from ffg articles for previewed cards.

**Comment by Kamalisk** [comment]
It also downloads jpgs because that is what they are. You can rename them to png and most things can just open them regardless.
