### ISSUE TITLE
Incorrect cost on new "On Your Own"

### ISSUE THREAD

**Issue by EdKaiser** [Kamalisk/arkhamdb#319]
The new On Your Own ([https://arkhamdb.com/card/53010](https://arkhamdb.com/card/53010)) is a permanent but Arkham DB incorrectly reflects a cost of 2 (I presume  a carry over from the original version).

**Comment by robert-huang** [comment]
should be fixed once https://github.com/Kamalisk/arkhamdb-json-data/pull/720 gets merged

**Comment by EdKaiser** [comment]
Verified fixed.  Thanks!
