### ISSUE TITLE
Broken pictures for Norman Withers' Vengeful Hound and Split the Angle

### ISSUE THREAD

**Issue by EdKaiser** [Kamalisk/arkhamdb#320]
The pictures for Norman Withers' investigator-specific cards are broken:
- Vengeful Hound ([https://arkhamdb.com/card/98009](https://arkhamdb.com/card/98009))
- Split the Angle ([https://arkhamdb.com/card/98008](https://arkhamdb.com/card/98008))

FWIW this oddly affects how the "deck testing" feature works:
![image](https://user-images.githubusercontent.com/12415112/89842190-c85e8080-db29-11ea-8a20-2d73c085b0ca.png)

**Comment by robert-huang** [comment]
they haven't been added to the website yet, it should resolve once those cards have images on the individual card pages

**Comment by EdKaiser** [comment]
Verified fixed.
