### ISSUE TITLE
Deck verification for Dunwich investigators

### ISSUE THREAD

**Issue by jayelbird** [Kamalisk/arkhamdb#33]
For Dunwich investigators, show an error if there are greater than 5 off-class cards included in the deck.

**Comment by sacrelicious2** [comment]
Another issue is that Rex Murphy isn't allowed Fortune traited cards, but nothing stops them from being added.

**Comment by Kamalisk** [comment]
Reworking the definition system for deck options, then the db should enforce the restrictions better (especially for Marie Lambeau)

**Comment by jayelbird** [comment]
I think the deck verification restriction may currently not be in place. Choosing a core investigator defaults to showing only cards from their classes, but it doesn't hide cards they can't play if you expand which classes are being shown or if you show 3-5 xp for their off-class.

**Comment by Kamalisk** [comment]
Valid cards for investigators should now be fixed, the data for the limits is there I just need to make it detect if you are over the limit.

**Comment by Kamalisk** [comment]
should respect all deck limits correctly.
