### ISSUE TITLE
admin panel - not working

### ISSUE THREAD

**Issue by Morphium84** [Kamalisk/arkhamdb#330]
Hello. When entering the admin panel, this error:

> An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_card" as such route does not exist.").

> Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_card" as such route does not exist.")." at /home/m/morphium84/arkham/src/AppBundle/Resources/views/Admin/index.html.twig line 8

screenshot - https://prnt.sc/u79uvs

What have I done wrong?

**Comment by Kamalisk** [comment]
we dont use the admin pages for anything, they should probably just be removed. They almost certainly dont work.

All data is managed through the json files.
