### ISSUE TITLE
Winifred Habbamock level 0 versions of Slip Away missing

### ISSUE THREAD

**Issue by phtevenck79** [Kamalisk/arkhamdb#376]
The Winifred Habbamock investigator starter deck, 2 x card number 14 is "Slip Away" but level zero. When Creating a deck on the website against this investigator, only the level 2 versions, card number 24 are listed.
![IMG_0963D](https://user-images.githubusercontent.com/50930805/102702191-cd5dda00-4257-11eb-815d-6804f59f233e.JPG)

**Comment by Veronica-212** [comment]
If you'll look at the remaining cards in the investigator starter decks, you'll notice that any cards that were already printed in another product are not listed.
Slip Away was first printed in The Forgotten Age (The City of Archives), so this is intentional, not an oversight.

**Comment by idlaviV** [comment]
This is not the case for the Stella deck: it still contains **Live and Learn**, **Rabbit's Foot**, **Dumb Luck**, **Oops**, **Take Heart** and **Look what I found**.
Related to  #397 (Chaos and duplicated cards ).

**Comment by elkeinkrad** [comment]
As I know, duplicated cards in stella deck were added first, and then others were added later ([#906](https://github.com/Kamalisk/arkhamdb-json-data/pull/906)). Due to handling "duplicated" cards, those cards were added recently. It seems that those cards are added currently.

**Comment by Kamalisk** [comment]
duplicate cards should be added and working now.
