### ISSUE TITLE
Deck list not displaying on my saved decks.

### ISSUE THREAD

**Issue by chippy2020** [Kamalisk/arkhamdb#377]
![image](https://user-images.githubusercontent.com/76670805/103184179-61ddc300-487c-11eb-92c4-fae6ce2042ee.png)

See above, happening in FF and Chrome.

**Comment by chippy2020** [comment]
This started working for me, not sure what fixed it.

**Comment by Kamalisk** [comment]
always make sure to clear the cache properly, if you encounter issues like this.
