### ISSUE TITLE
Card Submission?

### ISSUE THREAD

**Issue by clayton-grey** [Kamalisk/arkhamdb#38]
Is there a way to submit missing card info? I'd love to aid with new sets if there was a way to do so easily. If there is, pardon my density, but I can't seem to spot it!

**Comment by Kamalisk** [comment]
there is a seperate repo with the card data in json format.

**Comment by Kamalisk** [comment]
https://github.com/Kamalisk/arkhamdb-json-data you can submit pull requests yourself, or post issues in that repo and then they should get fixed eventually.
