### ISSUE TITLE
Users can like card reviews infinitely

### ISSUE THREAD

**Issue by davilimap** [Kamalisk/arkhamdb#384]
For newer cards, at least the Parallel Sets and The Innsmouth conspiracy, users can keep clicking the like button on card reviews. Haven't seen how far back this goes, but it doesn't seem to work for older cards.

See this review on Daisy's Advanced Weakness with 7000+ reviews: https://arkhamdb.com/card/90003

**Comment by bzly** [comment]
It works on older cards for me, I can like reviews on [Unexpected Courage](https://arkhamdb.com/card/01093) indefinitely.

**Comment by Kamalisk** [comment]
sadly this has been true forever. There is not a huge problem with it, but I can take a look to limit it to 1 vote per account.
I am unsure why someone would feel the need to hit the like button 7000 times, or if they took effort to write a script to do it. 
I guess if I ever want to add popular review sections I should definitely fix it :P

**Comment by Kamalisk** [comment]
Ok that only took 5 minutes to fix :P Was just a missing call to record the user voting. I will remove all "Likes" from reviews over 1000, as that is clearly false. Also people can still vote on the same ones they previously voted, only newly recording votes can't be duplicated.
