### ISSUE TITLE
Chaos and duplicated cards

### ISSUE THREAD

**Issue by elkeinkrad** [Kamalisk/arkhamdb#397]
As I know, duplicate_of key is currently added. For chaos deck, it seems that duplicated cards are picked independently.

I tried chaos deck for Stella, and both version of Live and Learn are picked.

![image](https://user-images.githubusercontent.com/41584047/109915043-7b740e80-7cf4-11eb-8050-d340b4e13272.png)

**Comment by Kamalisk** [comment]
should probably avoid duplicates now.
