### ISSUE TITLE
No way to search for asset cards by slot

### ISSUE THREAD

**Issue by sacrelicious2** [Kamalisk/arkhamdb#4]
There is no way to filter search results by asset card slot (i.e. Ally, Acccessory, 1-hand, etc).  I've attempted using the type, subtype and trait filters ( k:Ally ), but none of these work for this field.

**Comment by Kamalisk** [comment]
So I ran out of letters (s, l, o and t are all taken). Just need to decide on a random unused letter.

**Comment by sacrelicious2** [comment]
I see that 's' is currently used for subtype.  I've tried using it, but never figured out what it is filtering based on.  Is it something that AH uses?  If not, can we switch it to slot?

**Comment by Kamalisk** [comment]
can now search using z. (I am running out of letters, s is subtype which are currently only weaknesesses)
