### ISSUE TITLE
Clicking "Go To Card Page" while deck building should give a warning

### ISSUE THREAD

**Issue by sacrelicious2** [Kamalisk/arkhamdb#40]
The problem is that if you click this button while building a deck, you lose all the edits you were doing.

Maybe this should be a pop up on any sort of navigation away from the deckbuilding page?  Similar to the behavior you see on reddit and facebook when you try to navigate away from a page you were in the middle of posting from.

**Comment by Kamalisk** [comment]
The deck builder should remember the changes you made if you go back to the deck, if not, then that is the issue rather than the lack of a warning.

**Comment by sacrelicious2** [comment]
Confirmed that is not working.  

Repro steps:

When editing a deck, click on a card name and then click on "Go To Card Page".
Click Back button in browser.

Results: Edited values in deck are lost.

Found In: Chrome, multiple platforms

**Comment by Kamalisk** [comment]
opens in new window now.
