### ISSUE TITLE
[Feature Request] Set allowed packs in deck search to match collection & select all of a cycle

### ISSUE THREAD

**Issue by CATower** [Kamalisk/arkhamdb#401]
It would be great to have a button next to none or all that would set allowed packs equal to my collection. Since it defaults to all, and doesn't seem to save a custom selection, its often time consuming to reset the packs to match my collection.

Additional idea: Clicking the title of a cycle, would select all or none of that whole cycle at once, speeding up the selection process.

Cheers

**Comment by wicherekp** [comment]
Yes, please! That'd be awesome.

**Comment by TomBuZi** [comment]
Just entered to ask for this feature myself... ;-)

**Comment by Kamalisk** [comment]
added an option to select your collection in the decklist search now. (only works when logged and having selected your collection)
