### ISSUE TITLE
Versatile card 06167 not showing black star icon for not counting for deck size on akhamdb

### ISSUE THREAD

**Issue by andreamene** [Kamalisk/arkhamdb#409]
Versatile is a permanent card and therefore it does not count for deck size, but on My Decks is not showing the black star icon for not counting for deck size on akhamdb

**Comment by vidinufi** [comment]
None of the permanents are shown with a black star. Black star is only shown for cards that otherwise would be counted by type but are included because of deckbuilding rules and are not counted.

**Comment by Kamalisk** [comment]
Permanent cards just show in a permanent section.
