### ISSUE TITLE
Add "Exile" rules from Dunwich Legacy to Rules page.

### ISSUE THREAD

**Issue by sacrelicious2** [Kamalisk/arkhamdb#42]
Dunwich Legacy introduced a new rule to the game.  It would be nice if this could be added to the Rules page for easy reference.

**Comment by mplain** [comment]
I can add it if you scan the source material. I won't be getting my Dunwich box anytime soon.

**Comment by mattsigal** [comment]
![16010293_10154891019059808_383379364_o](https://cloud.githubusercontent.com/assets/1421758/21993253/e78122d2-dbe7-11e6-98b0-e53349633e46.jpg)

**Comment by mplain** [comment]
Ok, thanks! I think I'll add it to the FAQ when it gets published. Or the Dunwich Campaign Guide. Not the rulebook proper.

**Comment by mattsigal** [comment]
I dunno, if it was up to a vote I'd include it in the Rules page (https://arkhamdb.com/rules). It is already alphabetical, so an entry for exile would not be out of place there. This would be the page I would immediately go to, if I was in a game and this keyword came up and I did not know what it meant. If you really wanted to be fancy, you could include it as a new entry, and next to the title include the Dunwich Legacy symbol in brackets or something so readers know it isn't core.

**Comment by sacrelicious2** [comment]
I agree with Matt.  It should be added with the rest of the rules alphabetically.  As more expansions are released and we keep seeing new rules added, it would best to have them all in one place rather than having to remember where that specific rule came from.

**Comment by mplain** [comment]
I'm kinda concerned that it says "in The Dunwich Legacy". Like it's a cycle-specific thing. Although the rule itself seems pretty universal... Eh, maybe you're right.

**Comment by mplain** [comment]
Done.
https://arkhamdb.com/rules#Exile
