### ISSUE TITLE
Parallel Agnes spells

### ISSUE THREAD

**Issue by PhoenixKnight08** [Kamalisk/arkhamdb#430]
When using Parallel Agnes, after I add a higher-level version of Shriveling to the deck, ArkhamDB tells me I have too many copies of a card by title.

**Comment by cdburgess** [comment]
@PhoenixKnight08 is your deck public? If so, can you provide a link to look at the deck?

**Comment by PhoenixKnight08** [comment]
https://arkhamdb.com/deck/view/1525086

**Comment by cdburgess** [comment]
I found your issue...

2x  Shrivelling
1x  Shrivelling •••

You are only allowed 2 copies (regardless of level). Remove one of the `2x  Shrivelling` and you will be all set!

**Comment by PhoenixKnight08** [comment]
Did I misunderstand how Parallel Agnes works, then?  The way I thought it read was you pay the full cost of the higher upgrade and can leave the lower version in with the lower version not counting on either deck size or copies.

**Comment by cdburgess** [comment]
Ah! My bad. I should have read the card. I don't see anything in the code that would allow for the upgraded card. So that is definitely a code issue. Thanks for the heads up. I am not a code maintainer, but I will take a look and see if I can discover something. This is the correct place for your issue. But it may not be an easy fix.

**Comment by PhoenixKnight08** [comment]
Glad I could be of help, and thanks for not making me have to go back and reshoot two scenarios for my YouTube channel's summer campaign.  Admittedly, I'm terrible with code myself, but could you do something similar to what you do with story assets?  Just a random thought.

**Comment by cdburgess** [comment]
Looking at this issue, as I am becoming more familiar with the code, it looks like there is a hard-coded value in the DB that identifies the "deck_limit" for each card.

So the code basically needs to be able to allow up to 4 of each "spell" type card for this investigator. In addition, it must spend the appropriate amount of XP for 3 or more spells.

**Comment by Kamalisk** [comment]
we have code to let certain investigators set the ignore deck limit option on specific cards. It works for skids, but I guess it has not been enabled for Agnes and for spells.

**Comment by cdburgess** [comment]
It doesn't appear to be working for Skids either: https://arkhamdb.com/deck/view/213649

I am using the `Gambit` card **Daring Maneuver** which is causing the error.

**Comment by Kamalisk** [comment]
It is not automatic, there is an option for the cards to specify that it ignores the deck limits, and then it works fine.

**Comment by PhoenixKnight08** [comment]
I just looked, and there actually isn't an option to ignore deck limits on the lower-level spells.

**Comment by Kamalisk** [comment]
There isn't for spells now, as Agnes is not implemented :P It works for Skids and his gambit cards though.

**Comment by cdburgess** [comment]
Ah! I see. The "ignore limitation" is attached to the card, not the Investigator. So it's more of a manual do-it-yourself instead of an automated process that the investigator card does automatically.

**Comment by Kamalisk** [comment]
Added ignore limit to spells now, so can manually adjust things for Agnes as needed.

**Comment by PhoenixKnight08** [comment]
Just tested it, and everything works now.  Thanks for your help!
