### ISSUE TITLE
Unable to build with Novella versions of existing Investigators

### ISSUE THREAD

**Issue by stoplis** [Kamalisk/arkhamdb#432]
The novella versions of Roland, Jenny, Norman, Silas, Carolyn and Dexter are not available to build with. They aren’t available as either their own investigators or as alternative versions in the standard characters.
I tried to build Norman but it says his alternative signature and weakness cards are forbidden.

**Comment by cdburgess** [comment]
@stoplis I'm new to the code base, but this sounds like a data issue? It might get more traction here -> https://github.com/Kamalisk/arkhamdb-json-data

Maybe the cards are not yet in the data?

**Comment by Kamalisk** [comment]
The Norman bug was fixed, as for the rest, right now you just need to use the other version of the investigator to build the deck with. You should be able to add all their different special cards manually to the deck.
