### ISSUE TITLE
Favor of the Sun/Moon not on ArkhamDB

### ISSUE THREAD

**Issue by billybryan** [Kamalisk/arkhamdb#444]
Any chance this can get added to Arkham DB? I was leveling Dexter Drake and it's not on his list. 

Thanks!

**Comment by zzorba** [comment]
These should both be there (https://arkhamdb.com/card/07272) might need to check your collection settings if they aren't showing up by default.

**Comment by billybryan** [comment]
OMG....amateur hour. 🤦‍♂️ Thank you!
