### ISSUE TITLE
View as Checklist

### ISSUE THREAD

**Issue by mplain** [Kamalisk/arkhamdb#45]
Fix the length of Traits and Set columns.

Do we even need columns for Skill Icons and Traits?
I suggets leaving columns for:
Name - Class - Type - Cost - XP - Set - Sncounter Set

![1](https://cloud.githubusercontent.com/assets/7605827/21974104/c6433ec8-dbd5-11e6-983d-a794e0c7b3fe.png)

**Comment by Kamalisk** [comment]
I have adjusted the layout, I still prefer those columns but reduced the size of them and add an encounter set column to seperate theose. If you still hate it after I update re-open this :P

**Comment by mplain** [comment]
Almost!

![1](https://cloud.githubusercontent.com/assets/7605827/22085735/68da5d3a-dde6-11e6-88df-9df6dee911f7.png)

**Comment by Kamalisk** [comment]
the card name column is meant to take up the rest of the page. Given how long that set name is, I felt perhaps it might not be worth forcing that column to fill the longer names perfectly. Some encounter sets also have things like 15-18 which takes up even more space.

**Comment by mplain** [comment]
I would take the longest encounter set name available, and resize that column to fit it.

I'd rather have those rare cards with subnames be displayed on two lines (1st lane name 2nd line subname) IF both do not fit in one line. The way it is now, it's a dozen cards in a row that take up two lines each just for the sake of two digits.
