### ISSUE TITLE
Apply XP cost from cards in deck

### ISSUE THREAD

**Issue by Urethramancer** [Kamalisk/arkhamdb#48]
I added my decks to ArkhamDB after playing the first scenario, and after upgrading them. I noticed there was an Upgrade button, which I clicked to add my XP, but now I have 7 XP worth of upgraded cards AND 7 XP unspent according to the system! I consider this an inconvenient bug/oversight, although not earth-shattering.

**Comment by Kamalisk** [comment]
If you plan to upgrade with the system, then you should upgrade first, set your xp and then mage changes. Any XP spent prior to the upgrade is considered spent from a previous upgrade and is not taken into account.

If you "delete" the deck it should only delete the latest upgrade, so it will no longer say you have unspent xp. Then remove the xp cards, click upgrade and add the xp cards.

Note, deleting the deck on the decklist page via multiselect will delete all versions of that deck.
