### ISSUE TITLE
Parallel Wendy Alternate Back bug

### ISSUE THREAD

**Issue by ghost** [Kamalisk/arkhamdb#490]
Choosing Red Tide back from the dropdown menu reverts both the front and back to original.
Before:
![image](https://user-images.githubusercontent.com/95961544/149786184-9408d997-9b78-47b8-9512-ef5034294474.png)
After:
![image](https://user-images.githubusercontent.com/95961544/149786240-8d0ae5d2-3a34-4d55-834d-28f3c986fe1a.png)

**Comment by eeyogre** [comment]
FYI: I think I'm seeing the same thing for Agnes Baker (Bad Blood). It does appear to be correcting the investigator as it does show the correct deckbuilding requirements for the Bad Blood version and when saving and re-opening, the menus are set correctly.
