### ISSUE TITLE
Redraw treachery button doesn't work

### ISSUE THREAD

**Issue by sacrelicious2** [Kamalisk/arkhamdb#5]
When using the Card Draw Simulator, the Redraw Treachery button remains disabled after drawing a weakness card (in the opening hand of 5, or otherwise).  Button should probably be renamed "Redraw Weakness", as not all weakness cards are Treachery, for example Mob Enforcer, Silver Twilight Acolyte, Stubborn Detective.

Alternatively, it might be better if the button could be replaced with 'Reshuffle Selected'.  This would handle both the weakness situation and testing out cards like Arcane Initiate.

**Comment by Kamalisk** [comment]
ok it works on the deck view, but not on the deck edit.

**Comment by sacrelicious2** [comment]
After testing, it looks like the issue is that it only works with Treachery card types, while it should actually trigger on Weakness cards.  This includes Treachery, but also includes certain Asset (Necronomicon), Event (Dark Memories) and Enemy (Mob Enforcer, etc) cards.

**Comment by Kamalisk** [comment]
changed to redraw weaknesses now

**Comment by sacrelicious2** [comment]
Tested and found it still doesn't work.  Tested with this deck, on the cards 'Dark Memory' and 'Mob Enforcer', button remains disabled.

http://arkhamdb.com/decklist/view/13/the-agnes-baker-mysteries-1.0

**Comment by sacrelicious2** [comment]
Tested again and it's working fine... I the site hadn't updated yet, or my browser had cached the old version.
