### ISSUE TITLE
Feature Request: Deck search by investigator used

### ISSUE THREAD

**Issue by nspiess** [Kamalisk/arkhamdb#501]
I'd love to see a deck search by investigator being used.

My current approach is to take e.g. the first name of an investigator and search by deck name. In the hopes, that the investigator has been used.
However it would be way more useful to directly search by the investigator (e.g. with a dropdown) directly. All the decks are linked to a certain investigator already, so the info is there.

Hope this gets some consideration. 🙂

**Comment by nspiess** [comment]
One workaround is to search by a signature card of the respective investigator.. thanks @Kamalisk.

**Comment by Hounk** [comment]
Signatures would work as well, but you can even search for decks that have a specific Investigator card, just like any other card, in the "Cards used" entry field.

**Comment by nspiess** [comment]
aah.. nice. alright.. I'm not sure if this feature request is necessary then anymore...

![image](https://user-images.githubusercontent.com/29440287/162394803-a2c316bc-6414-423a-8912-e01b3cde8e69.png)
