### ISSUE TITLE
Down the Rabbit Hole doesn't subtract 1 xp for 2nd upgrade

### ISSUE THREAD

**Issue by ndrwkim** [Kamalisk/arkhamdb#505]
https://arkhamdb.com/card/08059

When using this card (in conjunction with Arcane Research if relevant), the first spell upgrade (Clairvoyance(0) to Clairvoyance(3)) properly costs 0 xp. However, the second spell upgrade costs the full amount (3 xp) when I expected it to cost only 2 xp.

Example: https://arkhamdb.com/deck/view/2055109

**Comment by kelly-de-haan** [comment]
I had the same problem, but then did get my discount for the third card I upgraded

**Comment by Eetami** [comment]
It doesn't seem to work if the two upgrades are of the same name. It applies the discount only if the two upgrades are different cards.
