### ISSUE TITLE
Murder at the Excelsior Hotel locations missing image/text

### ISSUE THREAD

**Issue by anaphysik** [Kamalisk/arkhamdb#506]
None of the locations for Murder at the Excelsior Hotel have images for their revealed side. Each of them is also missing a text entry for their **un**revealed side. (Same info, but in reverse: Only unrevealed side has image; text is only present for revealed side.)

Affected cardpages:
https://arkhamdb.com/card/84010
https://arkhamdb.com/card/84011
https://arkhamdb.com/card/84012
https://arkhamdb.com/card/84013
https://arkhamdb.com/card/84014
https://arkhamdb.com/card/84015
https://arkhamdb.com/card/84016
https://arkhamdb.com/card/84017
https://arkhamdb.com/card/84018
https://arkhamdb.com/card/84019

**Comment by zzorba** [comment]
opened https://github.com/Kamalisk/arkhamdb-json-data/pull/1126 to fix
