### ISSUE TITLE
/api/public/cards only returns player cards?

### ISSUE THREAD

**Issue by IdleMuse** [Kamalisk/arkhamdb#507]
Is this intended? Is the only way to get all scenario/encounter cards etc from the API to trawl every pack with the /pack endpoint?

**Comment by zzorba** [comment]
You need to add `?encounter=1`
https://arkhamdb.com/api/public/cards?encounter=1

**Comment by IdleMuse** [comment]
Brilliant, thanks. Is there documentation for what parameters are accepted? the autogenerated docs are sparse.

**Comment by zzorba** [comment]
I think that's the only parameter on the public api for cards at least.  there's also a /api/public/packs and an /api/public/taboos but they don't take arguments AFAIK.

**Comment by Kamalisk** [comment]
Updated the api doc to mention the encounter parameter!
