### ISSUE TITLE
Error when viewing deck

### ISSUE THREAD

**Issue by sacrelicious2** [Kamalisk/arkhamdb#51]
When trying to view a deck I built (https://arkhamdb.com/deck/view/13368), I am not seeing the cards display properly.  Opening developer tools, I am seeing the following errors:

13368:416 Uncaught SyntaxError: Unexpected token <
app.js:148 Uncaught ReferenceError: investigator is not defined
    at Object.e.get_invalid_cards (app.js:148)
    at Object.e.get_problem (app.js:148)
    at Object.e.get_layout_data (app.js:143)
    at Object.e.display (app.js:143)
    at Object.refresh_deck (09efa31.js:81)
    at Object.on_all_loaded (09efa31.js:109)
    at HTMLDocument.<anonymous> (app.js:157)
    at HTMLDocument.dispatch (jquery.min.js:3)
    at HTMLDocument.r.handle (jquery.min.js:3)
    at Object.trigger (jquery.min.js:3)

**Comment by sacrelicious2** [comment]
Unable to repro with other decks, even a cloned version of the above deck.

**Comment by sacrelicious2** [comment]
Confirmed that is occurs on chrome, IE and mobile.

**Comment by Kamalisk** [comment]
Somehow you created a deck with no investigator, so it has issues. If you have any idea of what you did before this happened that would be great.

**Comment by sacrelicious2** [comment]
I created a Rex Murphy deck, and got this issue after editing the deck.  I am able to successfully clone the deck, so at some level it knows what the investigator deck.

Inspecting in chrome, it looks like an error message was inserted in the arkhamdb.com\deck/view\13368 file

`	app.deck_history && app.deck_history.init(<br />
<b>Notice</b>:  Undefined index: 02025 in <b>/opt/nrdb/adb/src/AppBundle/Entity/Deck.php</b> on line <b>98</b><br />
`

**Comment by sacrelicious2** [comment]
Note that 02025 is Thinking on your feet, a card that I had in the original version of my deck but removed after editing, swapping it for another out-of-class card.

**Comment by Kamalisk** [comment]
error with history. fixed next update.
