### ISSUE TITLE
Card count inaccurate

### ISSUE THREAD

**Issue by Rinceart** [Kamalisk/arkhamdb#511]
The system does not count cards accurately. I have a 33-card card count with three cards that does not count toward my 30-card deck limit, but the system says I only have 29 cards. It counts one card mistakenly as one that does not count toward my deck limit. It is a non-published deck, but here is the link: https://arkhamdb.com/deck/view/2154375

**Comment by zzorba** [comment]
You need to enable deck sharing on your user settings so we can view that link.

Is one of the cards a Permanent keyword card, those wouldn't count towards deck size (since they aren't shuffled into your deck).  Story cards given out during campaigns also typically do not count.

**Comment by Rinceart** [comment]
You’re right. I did have a permanent card in there that I have not noticed. I only focused on the stars next to the usual cards.

Thanks!
- G.
