### ISSUE TITLE
Increase time before auto-logout

### ISSUE THREAD

**Issue by cdwfs** [Kamalisk/arkhamdb#513]
ArkhamDB's auto-logout timeout seems highly aggressive. I've lost count of the number of times I've logged in to make some deck changes, lingered for a few minutes reading card descriptions and weighing my options, clicked Save, and been taken to a login prompt because I've been quietly logged out (with all changes discarded). My banks & email accounts are far more forgiving about leaving me logged in without activity, and they're protecting actual sensitive personal data (vs. a card collection). Can the time before auto-logout be increased?

**Comment by Kamalisk** [comment]
It should be increased to many hours now. It was just set to the default on the php side. I also found it annoying, but always forgot to get around to increasing it.
