### ISSUE TITLE
Card data wrong for 05327

### ISSUE THREAD

**Issue by IdleMuse** [Kamalisk/arkhamdb#517]
https://arkhamdb.com/api/public/card/05327 mysteriously has some `real_traits` listed (`"Item. Weapon. Firearm. Illicit."`), despite obviously not having any.

Doesn't appear to be a problem with the source data? https://github.com/Kamalisk/arkhamdb-json-data/blob/d895e05cdbf6f5c65f0149e0e11712c3cce6afb5/pack/tcu/bbt_encounter.json#L36-L54 or I would have raised a PR.

**Comment by zzorba** [comment]
We likely misnumbered this card previously.  We should add `"traits": null` to the json for 05327 to address this on the next import (null can be left off normally, but adding it can be used to clear something if it was improperly set in the past.

**Comment by Kamalisk** [comment]
fixed it.
