### ISSUE TITLE
API only serves player cards

### ISSUE THREAD

**Issue by rushl** [Kamalisk/arkhamdb#52]
When using the API to examine card data, only player cards are returned. Some sets return no data at all, as they have no player cards. None of the cards with the "Mythos" class are served by the API.

Could it be related to the "Hide Encounter Cards" function?

**Comment by Kamalisk** [comment]
I use encounter=1 to include the encounter cards.

https://arkhamdb.com/api/public/cards/?encounter=1

**Comment by Kamalisk** [comment]
Since I changed the way spoiler works, I should probably change the default to return all again, but that should work for now.

**Comment by rushl** [comment]
That does work for all cards, but it does not when requesting cards of a specific set. For example: https://arkhamdb.com/api/public/cards/cotr.json?encounter=1 returns no data at all. 

Thanks!
