### ISSUE TITLE
Parallel Wendy "do:90037" search gets HTTP ERROR 500 page.

### ISSUE THREAD

**Issue by Douggernaut** [Kamalisk/arkhamdb#540]
|| Wendy crashes the search. do:XXXXX queries for other cards fails gracefully with "Your query didn't match any card."

**Comment by Douggernaut** [comment]
Possibly related to https://github.com/Kamalisk/arkhamdb/issues/489 and https://github.com/Kamalisk/arkhamdb/issues/490.

**Comment by Kamalisk** [comment]
it should work for wendy now. Will show all possible choices as usable.
