### ISSUE TITLE
Tracking deck evolution through campaign

### ISSUE THREAD

**Issue by Buhallin** [Kamalisk/arkhamdb#56]
While this is a fairly serious departure from the current system, I think it would be a huge boon for Arkham.

It would be very nice if we could manage decks by creating it initially, and then adding experience and swapping cards in/out based on that experience before locking it in for the next scenario.  Simple deck management doesn't quite do it - experience must be spent from step to step, not from original to now.  Specific requirements I'd suggest:

- Allow XP to be added
- When XP is added, the previous deck state is locked
- Once XP has been added, select both the added and removed card (what swaps for what matters for upgrades)
- Properly track Permanent cards as not needing a card to be removed
- Allow addition of story assets and weaknesses
- Allow spending of XP on things other than cards (side missions)
- Less important, but it would be a nice addition here if we could track the specific campaign/scenarios.  (e.g. Completed the Gathering, gained 6 XP).

**Comment by Kamalisk** [comment]
There is an upgrade button. 
It calculates the minimum costs for the cards you change
It does not support side quests.

**Comment by Kamalisk** [comment]
Permanent cards also work. 
Will close it, tracking specifc campaigns tracking is a seperate issue.
