### ISSUE TITLE
Scarlet Keys cards only show up in deckbuilder if the cycle is specified in options

### ISSUE THREAD

**Issue by TheKevling** [Kamalisk/arkhamdb#560]
As stated, if building a Rita deck (as an example) the Scarlet Keys cards only show up as eligible if you include the cycle filter (e:tskp). Without the filter, leaving it open to all eligible cards, the Scarlet Keys don't show up.

**Comment by ddbrown30** [comment]
This works fine for me (tested with Bob). Double check your setting in the collection tab and make sure you have The Scarlet Keys Investigator Expansion checked.
![Capture](https://user-images.githubusercontent.com/9253904/196502678-3554abd9-b27c-4171-a212-2e7112228cb4.PNG)

**Comment by TheKevling** [comment]
Thanks - you are right! I knew it flagged up cards not in your collection with '?' in decklists, but didn't realise it stopped them showing up in deckbuilding (which makes perfect sense now I think about it!)
