### ISSUE TITLE
In a situation where Holy Rosary is limited to 1 copy

### ISSUE THREAD

**Issue by ddbrown30** [Kamalisk/arkhamdb#569]
I'm not sure of the repro steps, but I've managed to put my deck into a state where Holy Rosary is being limited to a single copy. I've checked other decks of mine, using the same taboo list, and they work fine. I tried cloning the deck and the problem persists so it must be related to something I've done in the deck. I've looked at several other cards, including other accessory cards, and they all look fine.

Here's a link to the cloned version. Let me know if I can provide any other information. https://arkhamdb.com/deck/view/2484159

![Capture](https://user-images.githubusercontent.com/9253904/198846409-969b73d5-82e8-4e6f-9804-cdcd0badb78c.PNG)

**Comment by zzorba** [comment]
Check your collection settings, if you only have a single (original) core set selected, it will limit you to 1 copy.

**Comment by ddbrown30** [comment]
Yeah, that was it. No idea how that go changed. It's correct in all my other decks. Anyway, thanks for the help.
