### ISSUE TITLE
Broken site update?

### ISSUE THREAD

**Issue by matteopic** [Kamalisk/arkhamdb#597]
Since the end of November I noticed some pull request has been merged in arkamdb-json-data, but the arkhamdb site does not reflect that changes.
For example, now this URL https://it.arkhamdb.com/cycle/ptc/list/encounter have to offer the Italian version...but there are other changes in other languages not applied.

Does the site require a manual update or there are some issues with an automated procedure?

**Comment by Kamalisk** [comment]
specific examples? I update the languages at the same time, if there are errors in the files, I might not notice them and that stops all of that language from being updated.

**Comment by matteopic** [comment]
Some examples...
- This merged request https://github.com/Kamalisk/arkhamdb-json-data/pull/1236 translates into italian all encounters of carcosa campaign but looking at this url https://it.arkhamdb.com/cycle/ptc/list/encounter you can see no translation
- Same thing with https://github.com/Kamalisk/arkhamdb-json-data/pull/1221 but for the Night of the Zealot https://it.arkhamdb.com/set/core/list/encounter
- This is an example with DE language https://github.com/Kamalisk/arkhamdb-json-data/pull/1239, Looking in the commits I exepct to see ...`Runde +1`... in the card, but looking at https://de.arkhamdb.com/card/60515 you can see previous text.
- Last example with RU language... Look at the card name changes https://github.com/Kamalisk/arkhamdb-json-data/pull/1230/commits/0230212551760a7c6ead70cb9a00bd83ed232b49 and the card name in the website https://ru.arkhamdb.com/find?q=02084&sort=set&view=card&decks=all

**Comment by Kamalisk** [comment]
thanks for the examples. I figured it out. I was being really stupid, and running the updates on my dev database (which I use for testing). So all translations should be up to date now.
