### ISSUE TITLE
[BUG] Additional weaknesses

### ISSUE THREAD

**Issue by szwanger** [Kamalisk/arkhamdb#598]
I added The Devil • XV (https://arkhamdb.com/card/54015) to my deck because a campaign scenario required me to add a weakness.  However, ArkhamDB now says "Contains too many cards" even though this weakness doesn't (shouldn't) count towards my deck size.

(btw, it would be really useful to be able to permanently add a random basic weakness to a deck,or to add a random basic weakness of a specific type.)

**Comment by zzorba** [comment]
Can you post a link to the deck (after turning on sharing in deck settings)?  

Weaknesses aren't counted against deck limits, is there another card that might be causing your deck limit to be exceeded?

**Comment by szwanger** [comment]
Oh my gosh, you are absolutely right.  At some point I accidentally added a 31st card.  Sorry for making a fuss about nothing!
