### ISSUE TITLE
Garbled review on Charlie Kane's card page

### ISSUE THREAD

**Issue by benjaminou4412** [Kamalisk/arkhamdb#602]
https://arkhamdb.com/card/09018

Unsure if this is something to do with arkhamdb itself or some strange formatting in the review, but the top review from Valentin1331 on Charlie Kane's card page is clearly garbled to hell. Based on the comments in reply to the review, it was probably readable at some point.

**Comment by Kamalisk** [comment]
it seems to be fine again now? unsure why.

**Comment by Valentin1331** [comment]
Seeing this for some reason, it was an issue with my use of HTML in the review to centre text, which didn't work. Removing the wrong HTML part in the text fixed the review.
