### ISSUE TITLE
ArkhamDB Registration

### ISSUE THREAD

**Issue by Valkiera** [Kamalisk/arkhamdb#611]
Greetings,

  I am not receiving my email to reset my PW, or register an account. I believe I have previously set up an account, either way I can't get logged into the site.

Val

**Comment by Kamalisk** [comment]
I would send an email to s.arkhamdb.com with some of your details. Unsure what your account is based on this report :P

**Comment by Valkiera** [comment]
Thank you for the assistance :) Wasn't at all sure where to start!

**Comment by Valkiera** [comment]
I'm trying to gain access to my decks on ArkamDB. I'm unable to log on with what I thought was my PW, but can't seem to receive the email to reset my PW.

Thank you for the assistance, wasn't sure where to start.
