### ISSUE TITLE
Darrell Simmons card list is missing cards

### ISSUE THREAD

**Issue by StaffanBaloo** [Kamalisk/arkhamdb#616]
The Darrell Simmons card list lacks some cards. I have not made an exhaustive examination of the list, but it appears the problem is that multi-color Survivor cards are not shown unless he can use their other color at that level (so Ice Pick (1) is shown because Darrell can use level 1 Seeker cards, but Ice Pick (3) isn't).

**Comment by Kamalisk** [comment]
I think this is resolved.
