### ISSUE TITLE
Rules page formatting

### ISSUE THREAD

**Issue by Chr1Z93** [Kamalisk/arkhamdb#623]
The rules page (https://arkhamdb.com/rules) has a formatting issue. After the "Keys" section everything is bold and cursive:
![image](https://github.com/Kamalisk/arkhamdb/assets/97286811/1a32c01c-7d10-41fe-b6a7-bde796176c5e)

**Comment by kristoea** [comment]
Perhaps because a `> `is missing in `<b><i>Stable</i</b>` here: https://github.com/Kamalisk/arkhamdb/blame/69f776ce8b0d2f421104285bdb9d64a65fcb98f3/src/AppBundle/Resources/views/Default/rulesreference.html.twig#L1836
