### ISSUE TITLE
Alternate back Ashcan Pete deckbuilding rules not working correctly

### ISSUE THREAD

**Issue by antherem** [Kamalisk/arkhamdb#625]
"Ashcan" Pete with the alternate back is able to take level 0-3 Survivor cards and level 0-4 cards with the Improvised or Tactic trait, and up to 5 other level 0 Guardian cards, but there is an issue with decks that meet these rules being reported as containing forbidden cards. I believe it is the "up to 5 other level 0 Guardian cards" rule that isn't working
3167357 - "contains forbidden cards"
3182496 (clone of 3167357 with all non-Tactic Guardian cards replaced with Survivor cards) - no error message
3181446 (upgrade of 3167357 with one Dynamite Blast(0) replaced by On The Hunt(3)) - no error message

**Comment by Kamalisk** [comment]
I think this is resolved now once the deck is resaved.
