### ISSUE TITLE
Emergency Aid

### ISSUE THREAD

**Issue by mattsigal** [Kamalisk/arkhamdb#63]
Updating a deck for Miskatonic Museum and it appears that Emergency Aid is not being counted as a valid card for some reason (even though the overall tally of 33 cards is correct).

With Emergency Aid:
![screen shot 2017-02-16 at 17 22 24](https://cloud.githubusercontent.com/assets/1421758/23044051/8b27160c-f46c-11e6-9671-f6c8a0fd97e8.png)

Without Emergency Aid:
![screen shot 2017-02-16 at 17 22 36](https://cloud.githubusercontent.com/assets/1421758/23044055/8f3a6834-f46c-11e6-9aac-71a230344acf.png)

In the first screenshot, it should be a valid deck. Also, adding the 1x Emergency Aid also did not use up an XP point, as it should.

**Comment by Kamalisk** [comment]
was imported from cdgb and they had it as an encounter card for some reason. I guess something is missing from it.

**Comment by Kamalisk** [comment]
I am impressed you added it to a deck. I cant even find the card in the deck builder. Something weird is going on :P

**Comment by Kamalisk** [comment]
ok, it had no xp cost instead of 0 xp. Should work properly now once the card data is updated.
