### ISSUE TITLE
Parallel Jim is missing from ArkhamDB

### ISSUE THREAD

**Issue by stbennet** [Kamalisk/arkhamdb#630]
Parallel Jim was recently released: https://www.fantasyflightgames.com/en/news/2023/10/13/laid-to-rest/

Parallel Jim Front: https://images-cdn.fantasyflightgames.com/filer_public/8e/60/8e60b4bb-ffae-4119-ada2-1b973653dfc6/ahc_jimculver_cards_jimculver.png
4 $willpower 3 $intellect 3 $combat 2 $agility
$reaction After you reveal 1 or more $skull or $curse tokens during a skill test you are performing: Replenish 1 charge on an asset you control. (Limit once per round.)
$elder_sign effect: +2. You may treat this token as if it were a $skull or $curse token instead.
_"I know I can make the dead dance."_

Parallel Jim Back: https://images-cdn.fantasyflightgames.com/filer_public/9e/bf/9ebf1e8a-779f-4446-9291-2fc7fa95a192/ahc_jimculver_cards_jimculver_back.png
Deck Size: 30.
Deckbuilding Options: Mystic cards ($mystic) level 0-3, Spell and Cursed cards level 0-4, Neutral cards level 0-5, up to 5 other Survivor cards ($survivor) level 0.
Deckbuilding Requirements (do not count toward deck size ): Jim's Trumpet, Final Rhapsody, The Beyond, 1 random basic weakness.
Spirit Deck Size: 10.
Spirit Deckbuilding Options: 9 different Ally assets from any class level 0-2, Vengeful Shade.
Spirit Deck Instructions: Shuffle the "spirit deck" separately from your deck and place it next to The Beyond asset, facedown. This deck may be upgraded separately using your unspent experience.
_Jazz has been nothing but trouble for Jim since the day he picked up his daddy's trumpet. But the dead sure love it when he plays, so Jim has no intention of stopping._

Jim's Trumpet (Advanced): https://images-cdn.fantasyflightgames.com/filer_public/d0/93/d093c969-eb93-4246-bc17-bcc80bbd77fb/ahc_jimculver_cards_jimstrumpet.png
Cost: 2
Icons: $willpower $willpower $wild $wild
Traits: Item. Instrument. Relic.
Rules text: Jim Culver deck only. Advanced.
$reaction When a $skull or $curse token is revealed during a skill test you are performing, exhaust Jim's Trumpet: Heal 1 horror from each investigator and Ally asset at your location or a connecting location.
Slot: Hand.

Final Rhapsody (Advanced): https://images-cdn.fantasyflightgames.com/filer_public/69/be/69be7d81-5a35-4fdf-af95-522e833c0e1d/ahc_jimculver_cards_finalrhapsody.png
Weakness
Traits: Endtimes.
Rules text:  Advanced.
Revelation - Reveal 5 chaos tokens from the chaos bag. For each non-$elder_sign, non-$bless symbol token revealed, take 1 damage and 1 horror.

Vengeful Shade: https://images-cdn.fantasyflightgames.com/filer_public/11/c3/11c355ab-2944-49e4-aea6-f584b6b724fc/ahc_jimculver_cards_vengefulshade.png
Type: Weakness. Enemy.
5 $combat 2 health 5 $agility
Traits: Monster. Geist.
Hunter. Prey - Jim Culver only.
You may fight or evade this enemy while it is attached to The Beyond (as if it were engaged with you). If you succeed, discard it. If you fail, spawn it engaged with you.
Forced - When you attach a spirit to The Beyond via its forced effect: Vengeful Shade attacks you (even if it is not at your location).
2 $horror

The Beyond (front): https://images-cdn.fantasyflightgames.com/filer_public/65/b1/65b1b169-3dee-4f41-b60c-1f32335c3087/ahc_jimculver_cards_thebeyonda.png
Type: Asset.
Cost: -
Traits: Sanctum. Spectral.
Rules Text: Jim Culver deck only. Permanent.
Each attached spirit loses all printed traits and gains the Geist trait. When damage/horror would be placed on an attached spirit, it must be placed on Jim Culver, instead.
Forced - When your turn begins: Attach the top card of the spirit deck to The Beyond, as a spirit. If 4 or more spirits are attached, flip this card and resolve its text.

The Beyond (back): https://images-cdn.fantasyflightgames.com/filer_public/08/83/08833da5-fae1-4cd1-b8fe-74028d782855/ahc_jimculver_cards_thebeyondb.png
Forced - One at a time, choose each non-weakness spirit attached to The Beyond and reveal a random token from the chaos bag. If it is...
* ... an $elder_sign token: You may either heal 1 horror, or attach the top card of the spirit deck to The Beyond, as a spirit. (Do not reveal tokens for the spirit you attach after resolving this effect.)
* ... an $auto_fail token: Discard this spirit. Take 1 direct damage/horror.
* ... a $skull token: Discard this spirit. Heal 1 horror.
* ... a $cultist, $elder_thing, $tablet, or $curse token: You must either discard this spirit or take 1 direct damage.
* ... any other token: Discard this spirit.
Flip this card back to its asset side.
Reminder: Spirits attached to The Beyond are in play but only retain their names and text boxes. Spirits do not take up slots and do not have health or sanity values. When a unique spirit is attached to The Beyond, any other asset that shares its name and is already in play is discarded. Spirits are always discarded to the bottom of the spirit deck.
Story.

**Comment by Chr1Z93** [comment]
He's implemented now, so you can close this I think
