### ISSUE TITLE
Error importing json-data

### ISSUE THREAD

**Issue by fafranco82** [Kamalisk/arkhamdb#64]
I've just download this project (and json-data one) in my local directory, try to run command app:import:std, and this error show up:

```
Importing SubTypes...
NULLstringPHP Fatal error:  Call to undefined method AppBundle\Entity\Subtype::toString() in C:\Programacion\Git\Deckbuilders\arkhamdb\src\AppBundle\Command\ImportStdCommand.php on line 468

Fatal error: Call to undefined method AppBundle\Entity\Subtype::toString() in C:\Programacion\Git\Deckbuilders\arkhamdb\src\AppBundle\Command\ImportStdCommand.php on line 468


  [Symfony\Component\Debug\Exception\UndefinedMethodException]
  Attempted to call an undefined method named "toString" of class "AppBundle\Entity\Subtype".
```

It seems that maybe some bit of coding is missing. I can fix it, but my intention is to add I18N to the site (mainly Spanish translation), I want to be sure there is nothing not commited to github, so my future PR doesn't have many conflicts with your code.

**Comment by Kamalisk** [comment]
I think some stuff might not be committed, but I am unsure why it would cause that error.

**Comment by Kamalisk** [comment]
There is nothing related to the importstd command uncommitted. I am unsure how you are getting that error. The subtype does indeed not have a toString method though, I am guessing it is because the datbase is empty, I have never tested it on an empty db since I added the subtype.

**Comment by Gibernet** [comment]
I had then same problem as fafranco82, and I solved it filing the subtype table with the items stored in the file subtypes.json. After that I have run the command again and all has been fine. 

The only problem that I have now is that I don't know how to put the images of the cards. I would like to have a personal copy with the spanish version of the cards. Any help is wellcome.
