### ISSUE TITLE
[Bug] Versatile not working with Lily Chen

### ISSUE THREAD

**Issue by NikZar** [Kamalisk/arkhamdb#643]
I don't know if I am missing something.

Just added 5 level 0 cards with versatile (no firearms) and these deck error "Contains forbidden cards (cards not permitted by Investigator)" is shown:
![image](https://github.com/Kamalisk/arkhamdb/assets/1833749/b4aecbd0-c2ca-46d6-899c-a2273b4ae945)

Before the update:
https://arkhamdb.com/deck/view/3564325

After the update:
https://arkhamdb.com/deck/view/3578557

Maybe I give a wrong interpretation to the Versatile text?

**Comment by zzorba** [comment]
Versatile makes you take 5 extra cards but only 1 card can be outside of your normal deckbuilding rules. Looks like this deck added multiple non guardian/mystic cards.
