### ISSUE TITLE
Wrong name of Leather Jacket card in Polish language. Card not searchable because of that.

### ISSUE THREAD

**Issue by Sczurolap** [Kamalisk/arkhamdb#647]
Wrong name of Leather Jacket card in Polish language. 

This card:
https://pl.arkhamdb.com/card/60310

name in polish version should be: 
Skórzana kurtka.

Card not searchable because of that.

**Comment by edadesd** [comment]
@Sczurolap PR updating this name was merged, you can close this issue.
