### ISSUE TITLE
Wrong name of base Daring Maneuver card in Polish language. 

### ISSUE THREAD

**Issue by Sczurolap** [Kamalisk/arkhamdb#648]
Wrong name of Daring Maneuver card in Polish language. 

This card:
https://arkhamdb.com/card/03030

name in polish version should be: 
Brawurowy manewr

The leveled up version of the card has the proper name.

Card not searchable because of that and annoying as the base and leveled-up version have different names.

**Comment by edadesd** [comment]
Added this to https://github.com/Kamalisk/arkhamdb-json-data/pull/1389

**Comment by edadesd** [comment]
@Sczurolap  PR updating this name was merged, you can close this issue.
