### ISSUE TITLE
Runtime error for card slot

### ISSUE THREAD

**Issue by uurshin** [Kamalisk/arkhamdb#650]
On a local install, when I navigate to cards that have a slot, card-info.html.twig throws a twig RunTime Error : 

`Neither the property "format" nor one of the methods "format()", "getformat()"/"isformat()"/"hasformat()" or "__call()" exist and have public access in class "Symfony\Bridge\Twig\AppVariable".`

I see that the code for displaying the slot (example : "Hand") is : 
`{{app.format.slot(slot)}}`

That looks like js code and not twig syntax. If replaced with {{ card.slot }}, no more error.
On the production website, the slot is not displayed (no error, I suppose production has a way of ignoring them. **If so, can someone tell me how to ignore them ? That could be useful**).

I attach a example of the difference between the card page and the card modal (the later works).
If this bug is confirmed, I can provide a merge request.

![De_Vermis_Mysteriis_·_ArkhamDB](https://github.com/Kamalisk/arkhamdb/assets/41575605/d8f30499-a37e-446b-adfd-5fd995e0f01d)
<img width="851" alt="error" src="https://github.com/Kamalisk/arkhamdb/assets/41575605/89e4eedc-87ed-4fb0-8fcf-6b471cde9d08">

**Comment by Kamalisk** [comment]
yeah, errors are supressed on production. I have fixed this, and some other changes, which I will finish soon.

**Comment by uurshin** [comment]
Nice ! I am not a symfony expert, could you tell me what I need to change to suppress errors on local env too ? Could be useful to bypass errors that I know are in progress to be fixed.

**Comment by Kamalisk** [comment]
a bit late but you just need to run it is in dev mode rather that production (in the config I think)
