### ISSUE TITLE
Preston Fairmont has access to Bank Job

### ISSUE THREAD

**Issue by antilogos** [Kamalisk/arkhamdb#653]
Might be related to the fact that the card has the keyword «Illicit» and not «Illicit.» with the ending dot.

**Comment by edadesd** [comment]
I'm not able to repro this. I see Bank Job in the response for GET https://arkhamdb.com/find?q=do%3A05003 .

**Comment by antilogos** [comment]
Yes. The problem is that he should not have access to Illicit cards.
