### ISSUE TITLE
Let Me Handle This incorrectly marked as a forbidden card for Hank Samson

### ISSUE THREAD

**Issue by benjaminou4412** [Kamalisk/arkhamdb#655]
https://arkhamdb.com/deck/view/3720647

As seen in this decklist, the addition of "Let Me Handle This!" puts up the "Contains forbidden cards (cards not permitted by Faction or Agenda)" notification, even though "Let Me Handle This!" is a level 0 Spirit card within Hank's deckbuilding pool.

**Comment by zzorba** [comment]
Is it possible you have more than 10 hours in the deck? It's possible that's the message it might show if you're over the limit.

**Comment by benjaminou4412** [comment]
Oops, you're totally right!
