### ISSUE TITLE
Hit Me not available for Rex Murphy (parallel or normal)

### ISSUE THREAD

**Issue by skrelpulon** [Kamalisk/arkhamdb#657]
The card Hit Me is not available for either version of Rex Murphy. This should be available for both versions due to his 5 level 0 cards of any class/up to 5 other Rogue level 0 cards.

**Comment by mikecheb** [comment]
@skrelpulon Hit Me is _**Fortune**_-traited, so AFAICT under no circumstances can either back of Rex take this card due to his Deckbuilding Restrictions.

**Comment by skrelpulon** [comment]
Whoops... This is a classic "reading the card explains the card moment". Thank you
