### ISSUE TITLE
Signature cards as related card on investigator's card page

### ISSUE THREAD

**Issue by yhurtadov** [Kamalisk/arkhamdb#659]
Related cards seem to be only higher/lower exp version of the same card.
But [Hank's page](https://arkhamdb.com/card/10015) lists it's transformed version as bonded/related.
Having this but for every investigator card page with their signature(s) card(s) and weakness(es) would be neat.
I wanna learn php just to implement this

**Comment by Kamalisk** [comment]
Added investigator cards to the investigator pages now. Investigators with alternate cards such as roland, also list those too.
