### ISSUE TITLE
Show different "pip" variants of a card on one screen.

### ISSUE THREAD

**Issue by Gswp** [Kamalisk/arkhamdb#66]
It would be nice to have some kind of button to see all variants of one card at once navigating from one of those cards and not having to enter the name of the card. A button called "show variants" for example.

**Comment by Kamalisk** [comment]
a good idea now that we are getting a lot more upgrades. Should be linked on the card page at the very least.

**Comment by unitled** [comment]
Is it possible to add the number of pips in the various drop downs? So Lucky! or Lucky! (II)?

**Comment by Kamalisk** [comment]
what are the "various" drop downs? :P

**Comment by jgranata13** [comment]
I second this!!
