### ISSUE TITLE
Hemlock Vale campaign card issues

### ISSUE THREAD

**Issue by anaphysik** [Kamalisk/arkhamdb#660]
re: https://arkhamdb.com/card/10685

The Hemlock Curse story weakness has been implemented as Day of Rain 3-6, with the Endless Hunger subtitle. However, Day of Rain 3-6 are actually **4 different** The Hemlock Curse cards -- as each one has a different subtitle! (They have identical rules text and identical expansion number (185), which are reasons why this is very easy to miss.) Especially for when scans get uploaded, they should be 4 separate cards.

Day of Rain 3 is Endless Hunger
Day of Rain 4 is Echoing Voices
Day of Rain 5 is Withered Flesh
Day of Rain 6 is Knotted Growths

(Photo attached as evidence.)
![IMG_1368](https://github.com/Kamalisk/arkhamdb/assets/103298075/1d66d606-bbb1-4b75-bcc6-022ac566224f)

**Comment by fspoettel** [comment]
I think this issue should be closed here and transferred to https://github.com/Kamalisk/arkhamdb-json-data/ and discussed there. The FHV campaign encounters are a work in progress PR there, so there are more eyes / hands to check this. There is a work in progress PR for Hemlock Vale Campaign here: https://github.com/Kamalisk/arkhamdb-json-data/pull/1382

**Comment by Kamalisk** [comment]
Will close it and come back to it after the encounters are sorted.
