### ISSUE TITLE
Different filter behaviour between eng and ita website

### ISSUE THREAD

**Issue by alberto-bottarini** [Kamalisk/arkhamdb#661]
Same page, with different locale

https://arkhamdb.com/find?q=f%3Aguardian+p%3E2+z%3Aally&sort=name&view=list&decks=player&spoilers=hide

https://it.arkhamdb.com/find?q=f%3Aguardian+p%3E2+z%3Aally&sort=name&view=list&decks=player&spoilers=hide

The english one shows, correctly, some cards. The italian one does not show nothing.

I guess because "ally" is not a valid italian words. You should use "alleato". But the select in the filter page show "ally" even in the italian version.

**Comment by Kamalisk** [comment]
well I sort of fixed it. Sadly since not all cards are translated, the list is populated with both english and italian, so until they are all translated it will be a mix, but at least its better than only english.
