### ISSUE TITLE
[Feature Request] Suggestion: Ghosts of Onigawa and other fan-made content

### ISSUE THREAD

**Issue by Warenhari** [Kamalisk/arkhamdb#662]
Would be great to be able to use Player Cards from big fan-made expansions like "Ghosts of Onigawa" in ArkhamDB decks.

Would if be acceptable to add Collection item for "Ghosts of Onigawa" that could be populated with cards from this expansion?
I can provide at least basic support for it - like entering the parameters, and in future, moving card tests into the repo too.

It'll be a precedence as first fan-made content on ArkhamDB, but RingDB (Card DB for Lord of the Rings) had it and it was very helpful and welcome by most. As it's part of "Collection" selector, it's opt-in, so nothing is forced upon the user.

Regards

**Comment by Kamalisk** [comment]
I dont plan to add unofficial things to the site, there is enough work to maintain and support the real cards. It might be an idea to later on support entering custom cards manually for people, but that is probably not something I would do soon.
