### ISSUE TITLE
I registered but never received the email.

### ISSUE THREAD

**Issue by cmittendorf** [Kamalisk/arkhamdb#664]
Hi! I registered with an account, but I never received the email to verify my address (and it's not in the spam folder). Re-sending the email didn't work either. It seems that messages from your server are most likely blocked by my provider.

**Comment by Kamalisk** [comment]
I would need to know the account name or email to resolve it.

**Comment by cmittendorf** [comment]
My account is "mittibyn".

**Comment by Kamalisk** [comment]
should be enabled now.
