### ISSUE TITLE
Hank Samson (Resolute) front/back should be "linked"

### ISSUE THREAD

**Issue by 67protons** [Kamalisk/arkhamdb#665]
There are other cards in the database such as `Predator or Prey?` Code=`01121a` and `The Masked Hunter` Code=`01121b` that makes use of `linked` terminology such as:
* `linked_to_code`
* `linked_to_name`
* `linked_card`

I believe these same fields should be used for Hank Samson to link together `10016a` and `10016b`

**Comment by fspoettel** [comment]
I think this issue should be closed here and transferred to https://github.com/Kamalisk/arkhamdb-json-data/ and discussed there, as the `links` between card sides are defined in the json data. There are more eyes on that repo too.

**Comment by 67protons** [comment]
> I think this issue should be closed here and transferred to https://github.com/Kamalisk/arkhamdb-json-data/ and discussed there, as the `links` between card sides are defined in the json data. There are more eyes on that repo too.

👍 sounds good, mentioned it over there too
