### ISSUE TITLE
Pop-up UI missing "2" button for some cards

### ISSUE THREAD

**Issue by Minethlos** [Kamalisk/arkhamdb#666]
To replicate, I created a new deck with Ashcan Pete, tried to add "Lucky!" via pop-up (e.g., by searching and clicking on the appropriate card name), and this is what I see:
![image](https://github.com/Kamalisk/arkhamdb/assets/173623851/2f10a9b1-9e95-4c49-a212-f482ebe137a7)

The option to add the second copy of Lucky! is not there. There are no restrictions for this card for Pete, so this is a bug. I have seen this bug for other investigators, too (checked for Bob Jenkins) and other cards (checked for Hot Streak (4)).

**Comment by mikecheb** [comment]
It seems like you may need to edit your Collection to include 2 copies of the Core Set (or Revised Core), if that's what you own. Alternatively, you can use the Collection tab in the deckbuilder to change which packs should be treated as available.

Both `Lucky! (0)` and `Hot Streak (4)` are part of the Core Set, so if you've only marked that you own one copy, it'll only allow you to include 1.

**Comment by Minethlos** [comment]
Thanks @mikecheb, I had all sets enabled, but disabling and re-enabling all 3 core sets fixed the problem.
