### ISSUE TITLE
Illustrator search broken

### ISSUE THREAD

**Issue by ragados** [Kamalisk/arkhamdb#669]
I am unable to search for cards by Illustrator using l:illustrator
I have tested with several illustrators, both full strings and substrings. Nothing has works
Specific Illustrators tested:
Cristi Balanescu
Christ
christ
Christi
christi
Balanescu
Christopher Burdett
Burdett
burdett
burd

I have tested. across search pages on various parts of the site and the behaviour appears to be the same throughout
Also tested on Chrome Version 126.0.6478.185 (Official Build) (arm64), Firefox 128.0.2 (64-bit) and Safari Version 17.5

**Comment by Kamalisk** [comment]
It has to be exact and if multiple words has to have quotes. Tested with l:"Cristi Balanescu" and it returns results.

**Comment by ragados** [comment]
Given variance in names, exact matching seems foolish. And the need for
quotes is contrary to any of the other searches on the site?

**Comment by Kamalisk** [comment]
Quotes is consistent with all the other searches, aside from the text search which just searches card names, and then it just takes all words that arent part of the syntax and searches that. Quotes are only required if there is a space or other special characters in the term you are searching for. 

So if you want to find "Silver Twilight" traited cards, you need to put k:"silver twilight". k:silver twlight  will not work

Most fields dont do partial matches for performance reasons, and I can't imagine interested in all artists called Chris. You can even select an artist from a list on the search page if you need. I think this is good enough for most cases.

**Comment by ragados** [comment]
RJ Palmer or R.J. Palmer
Chris or Christopher
There are so many instances of this ambiguity that I'd generally only
search surname eg Palmer and risk capturing two artists in one search than
needing to be exact and coming away thinking the artist hasn't painted for
the game because I used the wrong version of their name.
