### ISSUE TITLE
search for decs containing cards like 'daredevil' only showing decks containing he lvl 2 version of the card not lvl 0

### ISSUE THREAD

**Issue by booy17** [Kamalisk/arkhamdb#676]
Hello,

When i search for decks that include Daredevil the results only show decks that contain the level 2 copy of Daredevil. 
[like this](https://arkhamdb.com/decklists/find?faction=&cards%5B%5D=06240&author=&name=&sort=popularity&packs%5B%5D=1&packs%5B%5D=1-2&packs%5B%5D=76&packs%5B%5D=2&packs%5B%5D=4&packs%5B%5D=5&packs%5B%5D=8&packs%5B%5D=9&packs%5B%5D=10&packs%5B%5D=11&packs%5B%5D=12&packs%5B%5D=13&packs%5B%5D=14&packs%5B%5D=15&packs%5B%5D=16&packs%5B%5D=17&packs%5B%5D=18&packs%5B%5D=20&packs%5B%5D=21&packs%5B%5D=22&packs%5B%5D=23&packs%5B%5D=24&packs%5B%5D=25&packs%5B%5D=26&packs%5B%5D=29&packs%5B%5D=30&packs%5B%5D=31&packs%5B%5D=34&packs%5B%5D=35&packs%5B%5D=36&packs%5B%5D=37&packs%5B%5D=38&packs%5B%5D=40&packs%5B%5D=41&packs%5B%5D=42&packs%5B%5D=43&packs%5B%5D=44&packs%5B%5D=45&packs%5B%5D=52&packs%5B%5D=56&packs%5B%5D=57&packs%5B%5D=58&packs%5B%5D=59&packs%5B%5D=60&packs%5B%5D=61&packs%5B%5D=73&packs%5B%5D=74&packs%5B%5D=79&packs%5B%5D=80&packs%5B%5D=84&packs%5B%5D=85&packs%5B%5D=28&packs%5B%5D=33&packs%5B%5D=39&packs%5B%5D=54&packs%5B%5D=72&packs%5B%5D=47&packs%5B%5D=48&packs%5B%5D=49&packs%5B%5D=50&packs%5B%5D=51&packs%5B%5D=3&packs%5B%5D=6&packs%5B%5D=27&packs%5B%5D=32&packs%5B%5D=46&packs%5B%5D=55&packs%5B%5D=70&packs%5B%5D=77&packs%5B%5D=81&packs%5B%5D=82&packs%5B%5D=19&packs%5B%5D=63&packs%5B%5D=64&packs%5B%5D=65&packs%5B%5D=66&packs%5B%5D=67&packs%5B%5D=68&packs%5B%5D=69&packs%5B%5D=7&packs%5B%5D=53&packs%5B%5D=62&packs%5B%5D=71&packs%5B%5D=75&packs%5B%5D=78&packs%5B%5D=83&packs%5B%5D=86&packs%5B%5D=87&packs%5B%5D=88&packs%5B%5D=89)
i can manually replace the card id by swapping the number in the url from "cards%5B%5D=06240" to "cards%5B%5D=60318" to have a search result that shows decks with the level 0 daredevil 
After some testing i think this is happening with all cards from the Winifred Habbamock starter deck set that have a different level version like lockpicks  
i have reset my collection on the site and tested it in a different browser without an account and i still get this behavior. i have also asked a friend and they have replicated this behavior.
 
Thanks,

**Comment by Kamalisk** [comment]
Updated the search to indicate which specific card you are finding, e.g. daredevil 0 or daredevil [2]. and which packs they come from to make it clearer which card is being searched for, and making it correctly search for the card.
