### ISSUE TITLE
Wrong links in localized site.

### ISSUE THREAD

**Issue by matteopic** [Kamalisk/arkhamdb#681]
Localized versions of arkhamdb have some issues with some links.
In the deck detail page, the link for each card always goes to the US version of that card.
The same thing happens when opening the card detail popup; the detail is in the correct language but the "Go to card page" button goes to the US version of that card.

**Comment by Kamalisk** [comment]
I fixed it for marvel, but thought I had fixed it here, but apparantly not. Have now.
