### ISSUE TITLE
Suggestion: API list favourite decks

### ISSUE THREAD

**Issue by JoaoPaul54** [Kamalisk/arkhamdb#691]
As of now, to retrieve a deck from someone else through the API we need to create a copy of it.

In most cases, I'd prefer to retrieve the favorite instead of a copy to stay aware of modifications.

Is this a possibility?

**Comment by Kamalisk** [comment]
Private decks which are set to public can be accessed with the api (/api/public/deck/{deck_id})

If you need to access private decks, then it will require oauth,

If you mean accessing a list of decks marked as favourite, then I don't think that is supported.
