### ISSUE TITLE
[Bug] Bracket search terms break card search in deck editor

### ISSUE THREAD

**Issue by MrZeyami** [Kamalisk/arkhamdb#693]
Using terms like [willpower] or [skull] or [bless] to find these icons on cards instead breaks the search function entirely.
Confirmed the issue present on chrome and firefox.

To replicate:
1) Open a deck in edit or upgrade
2) Type "x:(any [symbol])" into the search bar
Search will no longer update results

**Comment by Kamalisk** [comment]
the search accepts regular expressions, so [ is special character. You can just search for bless or put quotes around the search "[bless]" to search for the icon.
