### ISSUE TITLE
Dunwich Basic Weakness count

### ISSUE THREAD

**Issue by BDFlory** [Kamalisk/arkhamdb#72]
The basic weaknesses included in The Dunwich Legacy should be 2 available, like Paranoia and Amnesia, rather than 1. The random weakness function should reflect this, as well.

The correct odds on the various weaknesses obviously impacts deckbuilding, but it's also possible to have multiple copies in a deck thanks to some resolutions and standalone mode.

**Comment by Kamalisk** [comment]
updated the deck limit for them. the random weakness is not great at the moment but plan to improve it later.
