### ISSUE TITLE
Update XP available and Persistent Notes for Campaign Play

### ISSUE THREAD

**Issue by mattsigal** [Kamalisk/arkhamdb#73]
Am working on a campaign, and something went weird with arkhamdb in that it says I have more XP available to spend then I should have for one of my decks. I would like to correct this somehow, but don't see a way how (maybe click "upgrade deck" then put in a negative value?).  Would it be difficult to make this area modifiable?

![screen shot 2017-03-17 at 19 24 42](https://cloud.githubusercontent.com/assets/1421758/24066281/636d6318-0b47-11e7-99ef-ed950c27346d.png)

These values are very wrong. Maybe in the Notes tab, have two buttons to let users fix this manually: Add Experience Point, Remove Experience Point.

Also, when using the "Upgrade deck" button, could there please be a setting to copy the Notes area into the new version of the deck by default?  I keep the campaign log in the notes area, and this would save some hassle.

**Comment by Kamalisk** [comment]
I thought it did copy the notes, but I guess not :P 
As for the xp thing, it should always be correct (ignoring side quests)
What is the deck id of the deck with the problem?

**Comment by mattsigal** [comment]
Haha, yeah - it would be handy (and I would have thought it would be the default), but not at the moment.

I know it should always be correct, but I think I might have goofed (the third list is just the second list with the appropriate basic weakness added), and I can't tell exactly where the XP went wrong. This is the list in question: https://arkhamdb.com/deck/view/24214 and it should have 4 XP available at this point).

**Comment by Kamalisk** [comment]
you can delete an upgrade if you make a mistake on the xp.

**Comment by Kamalisk** [comment]
and it just goes back the previous deck.

**Comment by Kamalisk** [comment]
notes should persist now.

**Comment by mattsigal** [comment]
That is great about the notes. Regarding the XP issue, I guess my issue is I'm not sure when exactly I made the mistake so didn't want to go back deleting decks/changes if there was an easier solution. If this issue isn't common, then no worries :)

**Comment by Kamalisk** [comment]
easiest solution is to gain 1 less xp in the next scenario. Will perhas fix it when I add side quest support, will close for now.
