### ISSUE TITLE
JavaScript Error: "Object doesn't support property or method 'repeat' "

### ISSUE THREAD

**Issue by andrewwburns** [Kamalisk/arkhamdb#78]
I was trying to replicate the issue in #77 under IE11.0.10240.17202 and when I went to ( https://arkhamdb.com/deck/view/14510 ) I received the following Console Error:

![image](https://cloud.githubusercontent.com/assets/13449428/24454427/c0027452-1483-11e7-8a59-490c6469d00a.png)

No images, cards, etc.. loaded.

**Comment by andrewwburns** [comment]
I believe that the issue is with app.format.js, line 15. It seems that the 'Repeat' method is EMCA 2015 - which naturally IE11 doesn't fully support. Edge does, along with Chrome and Firefox, and the problem doesn't appear there.

![image](https://cloud.githubusercontent.com/assets/13449428/24456005/7916a99a-1489-11e7-9135-dfe9af2ba546.png)

https://docs.microsoft.com/en-us/scripting/javascript/reference/repeat-method-string-javascript

Might I suggest the following

`"******".slice(-xp);`

Rather than repeating the * for xp times, this slices off xp asterisks, and this should be backwardly compatible. Of course, IE11 might have other issues too. Also, this assumes we don't end up with cards that have, say 7 XP pips...

**Comment by Kamalisk** [comment]
will be fixed when I next update live.
