### ISSUE TITLE
Feature Request: Multiple Languages for Cards

### ISSUE THREAD

**Issue by Gavrahil** [Kamalisk/arkhamdb#80]
As a German Player of Arkham Horror LCG, it would be a massive boon, to have some kind of localization for the Card Titles and Texts. Maybe a user could set up his preferred language in his Collection or something like that.
Thanks for the great work

**Comment by martinborda** [comment]
This would be great. I can help to translate to Spanish if this feature becomes true (I own base game).
I would like just to say that English should be default language, in case a translation for a card is not set.

**Comment by Landen13** [comment]
+ for this feature
I would like to help in translation to Russian

**Comment by Szczurolap** [comment]
Yep, multiple languages version will be very handy. I see that the source - ThroneDB has this feature, so maybe it make it easier to implement?

I'm ready to take care of polish language version, when multiple language version become available.

**Comment by Kamalisk** [comment]
added placeholder files for translations:
https://github.com/Kamalisk/arkhamdb-json-data/tree/master/translations

If you want to translate, make changes and enter the pull requests.

**Comment by DonScovillo** [comment]
From what I can see, the German translations have all been made.

**Comment by Gavrahil** [comment]
What are you talking about? The files habe been set up by Kamalisk, but I am still in the process of translating everything. Most of it is still in its English original

**Comment by ghost** [comment]
OK, I see that Polish translations not started. Haw can help you in that?

**Comment by Gavrahil** [comment]
I don't speak polish at all. So if you wanted to help, you can go to the link above, go to the pl/ folder and start translating the files.
