### ISSUE TITLE
"Asset Slots" stat doesn't take into account campaign assets

### ISSUE THREAD

**Issue by EY3G0R3** [Kamalisk/arkhamdb#81]
This is a minor thing, however in the screenshot below, "Dr. Francis Morgan" and "Dr. Henry Armitage" are not counted towards ally slot, showing incorrect number (2) instead of 4. (other allies are Peter Sylvestre and Dr. Milan Christopher)
![arkham - stats](https://cloud.githubusercontent.com/assets/26953391/24739582/85711acc-1a51-11e7-838e-ec061cdc8199.png)

**Comment by Kamalisk** [comment]
fixed in next update.
