### ISSUE TITLE
"Permanent"/investigator-specific cards are getting included in the card draw simulator

### ISSUE THREAD

**Issue by EY3G0R3** [Kamalisk/arkhamdb#82]
Another minor thing, however in the screenshot below "Duke" is included in the card draw, even though he starts the game on the table and not in the deck.
With further testing, "Charisma", which is a permanent asset, also shows in the simulator.
Not a big deal in itself, however if permanent cards are taken into account for the calculation of draw odds, **card draw odds shown on the website might be wrong**.

![arkham - duke](https://cloud.githubusercontent.com/assets/26953391/24739798/b2d0d826-1a52-11e7-8e49-94e426163b4f.png)

![2017-04-05 22_52_33-deckbuilder arkhamdb](https://cloud.githubusercontent.com/assets/26953391/24739789/a2f79818-1a52-11e7-8f6f-6a7b6cf2a4ce.png)

**Comment by Kamalisk** [comment]
duke is a special card, and is not permanent (by definition of permanent). I can fix it for permanent cards but Duke will be there unless I add super special code just for Duke.

**Comment by LaszloKoller** [comment]
Actually, the _"Ashcan" Pete_ investigator card is the card with the special ability; _Duke_ is a rather 'vanilla' (standard) Asset card--other than being specific to an _"Ashcan" Pete_ deck, that is.

@Kamalisk: I'm sure _"Ashcan" Pete_ won't be the last investigator requiring specialized card handling. Something to consider as the number of investigators increases. You may want to implement an optional metadata concept for investigator cards, which would allow you to run special (one-off) code if and as needed.

**Comment by Kamalisk** [comment]
fixed. duke is hard coded for now.
