### ISSUE TITLE
Request to have card set/number in cardlist/print view

### ISSUE THREAD

**Issue by wakasm** [Kamalisk/arkhamdb#84]
Very small quality of life improvement.

I've found sorting my cards by the set number to be the most efficient way of ordering things, it would be awesome if when viewing and/or printing card lists for a deck, to be able to see the set and card number.  

Especially for printing - you have the ability to sort by set deck/number, but it doesn't actually output the value, such as:  Core Set #4.

Thanks.

**Comment by Kamalisk** [comment]
should show it when sorting by set number when I next update.
