### ISSUE TITLE
Unable to Edit Card Review

### ISSUE THREAD

**Issue by andrewwburns** [Kamalisk/arkhamdb#87]
I tried editing a card review I'd written (It's Essex County, not Exeter County), but was unable to. It would show me the edit page, but when I tried to save the change, I was shown the message: 

> Unable to find review

This does seem to be repeatable on my machine.

![screen shot 2017-04-15 at 15 51 52](https://cloud.githubusercontent.com/assets/13449428/25064541/0cb3749a-21f4-11e7-972c-98c1b663002c.png)

This was using Safari 10.0.3 on OSx. I'm not in the office much at the moment, or I'd try under Chrome, Firefox and IE too.

**Comment by Kamalisk** [comment]
Is it just this review or others? editing a review works for me at least.

**Comment by andrewwburns** [comment]
Hmm. Weird. I was finally getting around to following up on this - and it worked just fine. I was able to edit the review without an issue. 

Strange,  but I guess that for now this should be closed...  (I swear it didn't work!)
