### ISSUE TITLE
Keen Eye (and maybe other Permanent cards) still count towards deck size

### ISSUE THREAD

**Issue by mattsigal** [Kamalisk/arkhamdb#88]
Added Keen Eye (https://arkhamdb.com/card/02185) to a deck. This card has the Permanent keyword (https://arkhamdb.com/rules#Permanent), so it should not count toward my deck size. However, it still does.

EDIT: It seems Charisma is coded correctly, so there is some Permanent support already available?

**Comment by Kamalisk** [comment]
fixed. just not flagged as permanent.
