### ISSUE TITLE
Values scaling per investigator

### ISSUE THREAD

**Issue by mplain** [Kamalisk/arkhamdb#9]
Add extra fields:
"health_per_investigator" (for Ghoul Priest)
"clues_fixed" (for locations and acts with fixed clues, e.g. Sleeping Car)

**Comment by mplain** [comment]
The Rougarou also has scaling health.

**Comment by Kamalisk** [comment]
added the database fields. Just need to make it show in the UI now. Is the data already in the json?

**Comment by Kamalisk** [comment]
now shows up on the card pages.
