### ISSUE TITLE
Card sort by number acting weird

### ISSUE THREAD

**Issue by mattsigal** [Kamalisk/arkhamdb#93]
Just a small issue: when you sort a deck by faction then number, it should sort them Core Set (1-XXX), then Dunwich legacy (1-XXX), then the next big box, et cetera.

Right now, it appears that the sets are being ordered alphabetically first? For example:

![screen shot 2017-05-17 at 13 42 13](https://cloud.githubusercontent.com/assets/1421758/26168011/aaa4ed98-3b06-11e7-91ec-ea2f8a11994c.png)

In this screen shot, The Blood on the Altar cards (2x Prepared for the Worst) should appear at the bottom (Dunwich Legacy card #184), not at the top.

**Comment by mattsigal** [comment]
Perhaps this should be a new sort: `Faction -> Release Date`?  That would automatically put the cards in the order most useful to me (and anyone else who stores their cards this way).

**Comment by Kamalisk** [comment]
should sort by set and number for the number sort now.

**Comment by mattsigal** [comment]
Thank you!
