### ISSUE TITLE
Italian translation request

### ISSUE THREAD

**Issue by DevGizmo86** [Kamalisk/arkhamdb#94]
Hi Kamalisk and all arkhamdb staff.
It would be nice to have arkhamdb translated in italian language.
I would like to offer my help to translate cards and other stuff! I never used github before but I have some programming skills.
If you want to explain me how to do the translations, I will start this job as soon as possibile.

Thanks in advance!
Simone from Italy

**Comment by yucendulang** [comment]
It would be nice to have arkhamdb translated in chinese language too.
If you agree,we will help.

**Comment by Kamalisk** [comment]
If I get around to looking over what has been done for the spanish translation will let people know about other translations

**Comment by txkun** [comment]
+1 for Italian. Would love it.

**Comment by Kamalisk** [comment]
Have created placeholder files for the translations. Translate the text, make pull requests and I can see about getting it on the site. 

https://github.com/Kamalisk/arkhamdb-json-data/tree/master/translations

**Comment by DevGizmo86** [comment]
Thanks Kamalisk, we are working on the translations! :)

**Comment by Kamalisk** [comment]
sorry for taking so long but italian should be live now. thanks to those who added translations.
